/* =========================================================
   ZenAI Mystery Universe
   Series 02: The Last Timeline
   File: timeline-games.js
   Version: Playable Story Data v1.4

   本版重点：
   1. 修正 ACT02 没生效问题
   2. 强化 EP.01 - EP.10 ACT01
   3. 强化 EP.11 - EP.20 ACT02
   4. 新增强化 EP.21 - EP.30 ACT03
   5. 保留 EP.31 红眼宇宙彩蛋
   6. 保留 EP.39 Eli 视角反转
   7. 保留 EP.50 Hold On / Let Go 终章逻辑
========================================================= */

const timelineMeta = {
  universe: "ZenAI Mystery Universe",
  seriesId: "series-02",
  cnTitle: "最后的时间线",
  enTitle: "The Last Timeline",
  version: "v1.4",
  theme: "Time Travel / Sacrifice / Love / Letting Go",
  coreTime: "11:11 PM",
  coreProp: "Broken Watch",
  logline:
    "You spent 49 timelines trying to save Eli. In the 50th, you discover Eli was saving you too.",
  finalQuote: "In every timeline, I chose the one where you lived.",
};

const timelineEpisodes = [
  {
    id: 1,
    title: "The Night You Lost Them",
    subtitle: "The first time 11:11 PM took Eli away.",
    traveler: "You",
    prop: "Broken Watch",
    clockMode: "normal",
    visualMode: "blue",
    fragmentType: "message",
    mainText: [
      "At 11:08 PM, Eli sends a message that feels wrong before you even finish reading it.",
      "\"Don’t come looking for me.\"",
      "There is no explanation. No emoji. No second message. Just five words sitting on your screen like a door closing from the other side.",
      "You call once. No answer. Twice. No answer. By the third call, your hands are already shaking.",
      "The city outside is soaked in rain. Streetlights smear across the pavement. Somewhere far away, a clocktower begins to ring even though there is no clocktower in this neighborhood.",
      "At 11:11 PM, you reach the crosswalk.",
      "White light swallows everything.",
      "When your vision returns, Eli is gone. No body. No ambulance. No witnesses. Only a broken watch lying beside a spilled cup of coffee.",
      "The watch hands are frozen at 11:11 PM.",
      "You fall to your knees and scream Eli’s name until your throat stops sounding like yours.",
      "Then the entire world goes silent."
    ],
    choiceText: "Wake Up",
    quote: "Some nights do not end. They reset.",
    endingHint:
      "You open your eyes at 7:00 AM. Your phone buzzes. Eli is alive.",
  },

  {
    id: 2,
    title: "The Message That Shouldn’t Exist",
    subtitle: "A warning appears before you ever write it.",
    traveler: "You",
    prop: "Unsent Message",
    clockMode: "normal",
    visualMode: "blue",
    fragmentType: "message",
    mainText: [
      "You wake up gasping, still feeling rain on your skin.",
      "Your room is bright with morning. The same shirt is on the chair. The same cup is on your desk. The same notification waits on your phone.",
      "Eli: \"Coffee later?\"",
      "For three seconds, your heart believes mercy exists.",
      "Then you notice another message sitting in your draft box. It has no recipient. It has no timestamp. It is written in your own typing style, but you have no memory of writing it.",
      "\"You have tried this before.\"",
      "Below it, more words appear slowly, as if someone is typing from inside the screen.",
      "\"Do not trust 11:11 PM.\"",
      "You call Eli immediately. They answer with a sleepy laugh, annoyed and alive.",
      "\"You sound like you saw a ghost,\" Eli says.",
      "You almost tell them the truth. Instead, you ask them not to go near the east crosswalk tonight.",
      "Eli pauses.",
      "\"How did you know I was going there?\""
    ],
    choiceText: "Call Eli",
    quote: "The future left a warning in your own hands.",
    endingHint:
      "Eli says a sentence you heard after their death, before they ever had a chance to say it.",
  },

  {
    id: 3,
    title: "One More Morning",
    subtitle: "You try to stop the day before it begins.",
    traveler: "You",
    prop: "Broken Watch",
    clockMode: "normal",
    visualMode: "blue",
    fragmentType: "watch",
    mainText: [
      "This time, you do not wait for fate to start moving.",
      "You arrive at Eli’s door before breakfast. You knock too hard. You say too much. Your voice breaks in all the wrong places.",
      "Eli opens the door in an old sweater, holding a mug of coffee, alive in a way that hurts more than the memory of losing them.",
      "You tell them you had a dream. You say the day feels unsafe. You say staying home would make you feel better.",
      "Eli studies your face for a long time.",
      "\"You are terrible at pretending this is just anxiety,\" they say.",
      "But they stay.",
      "For the first time, the day changes.",
      "No crosswalk. No rain-soaked street. No final message. You make dinner together. You keep looking at the clock and pretending you are not.",
      "At 11:10 PM, Eli squeezes your hand.",
      "\"See? We made it.\"",
      "At 11:11 PM, the ceiling light flickers.",
      "The broken watch in your pocket starts ticking backward.",
      "A sound like tearing metal moves through the apartment walls.",
      "The accident has followed you inside."
    ],
    choiceText: "Hold Eli Back",
    quote: "Fate does not need a street to find someone.",
    endingHint:
      "The room bends around Eli. You reach for them, and the morning restarts.",
  },

  {
    id: 4,
    title: "The Broken Watch",
    subtitle: "The watch remembers what you cannot.",
    traveler: "You",
    prop: "Broken Watch",
    clockMode: "normal",
    visualMode: "blue",
    fragmentType: "watch",
    mainText: [
      "On the fourth morning, you stop screaming.",
      "You sit on the floor and empty your pockets with the calm of someone who has run out of disbelief.",
      "Keys. Phone. Receipt. A small piece of glass.",
      "And the broken watch.",
      "It should have been left in the rain. It should have belonged to the night Eli vanished. It should not be here, warm from your pocket.",
      "The hands are still frozen at 11:11 PM.",
      "You turn it over and find engraving beneath scratches and old blood.",
      "\"For the one who must live.\"",
      "You do not remember receiving it.",
      "You press the side button. The cover opens.",
      "Inside is a tiny photograph of Eli. Not from yesterday. Not from any photo you remember taking.",
      "In the picture, Eli looks older. Tired. Smiling like they are trying not to cry.",
      "Behind the photograph, there is a folded strip of paper.",
      "It says only one thing:",
      "\"When the watch breaks completely, one of us stays gone.\""
    ],
    choiceText: "Open The Watch",
    quote: "A gift from a future that has not forgiven you yet.",
    endingHint:
      "For the first time, the watch ticks once without moving its hands.",
  },

  {
    id: 5,
    title: "The Street With No Cars",
    subtitle: "You remove the accident. The ending remains.",
    traveler: "You",
    prop: "City Map",
    clockMode: "normal",
    visualMode: "blue",
    fragmentType: "photo",
    mainText: [
      "You decide the universe is not magic. It is a system. A system can be broken.",
      "You map the street. Every traffic light. Every alley. Every camera. Every possible route Eli might take.",
      "You call in a false emergency to block the east crosswalk. You report a gas leak. You make sure no cars can pass within three blocks.",
      "By 10:55 PM, the street is empty.",
      "By 11:05 PM, Eli is safe beside you, confused but trying to trust you.",
      "By 11:10 PM, the rain stops.",
      "The silence feels like victory.",
      "Then every traffic light turns red at once.",
      "At 11:11 PM, Eli looks at you and says, very softly, \"I think I have been here before.\"",
      "You grab their hand.",
      "Nothing hits them.",
      "No car. No white light. No scream.",
      "Eli simply disappears.",
      "Their fingers vanish from inside your grip, leaving only warmth behind.",
      "On the empty road, one shoe remains beneath the traffic signal.",
      "The digital crossing sign flashes:",
      "\"TIMELINE CORRECTION FAILED.\""
    ],
    choiceText: "Search The Street",
    quote: "The accident was never the cause. It was only the shape grief chose first.",
    endingHint:
      "A security camera captures the empty street. In the reflection, someone behind you is holding another watch.",
  },

  {
    id: 6,
    title: "The Train They Never Took",
    subtitle: "The first time the clock fights back.",
    traveler: "You",
    prop: "Train Ticket",
    clockMode: "warning",
    visualMode: "blue",
    fragmentType: "ticket",
    mainText: [
      "You stop trying to control the street. You choose distance instead.",
      "A train leaves the city at 9:40 PM. It does not pass the crosswalk. It does not pass the apartment. It does not pass any place where Eli has died.",
      "You buy two tickets with hands that know the route before your mind does.",
      "Eli follows you onto the train because they are beginning to understand one terrifying thing:",
      "You are not afraid of something that might happen.",
      "You are afraid of something that already has.",
      "At 10:49 PM, the train leaves the city.",
      "For twenty minutes, the world feels breakable in a good way.",
      "Eli leans against the window and says, \"Maybe we really can leave it behind.\"",
      "At 11:08 PM, the carriage lights turn cold blue.",
      "At 11:09 PM, every passenger stops moving.",
      "At 11:10 PM, the clock above the door begins to shake.",
      "At 11:11 PM, the speakers crackle.",
      "\"Timeline 006 will terminate at 11:11 PM.\"",
      "Every passenger turns toward Eli.",
      "Their mouths open together.",
      "\"Return what was borrowed.\""
    ],
    choiceText: "Run Through The Train",
    quote: "Changing direction is not the same as escaping fate.",
    endingHint:
      "Eli looks at the frozen passengers and whispers, \"Why does this feel familiar?\"",
  },

  {
    id: 7,
    title: "A Door Opens Twice",
    subtitle: "Another version of you knows the rule.",
    traveler: "You",
    prop: "Old Door",
    clockMode: "normal",
    visualMode: "blue",
    fragmentType: "door",
    mainText: [
      "The door appears on the seventh morning.",
      "It stands at the end of your hallway where there has only ever been a blank wall.",
      "Old wood. Brass handle. A scratch near the lock shaped like 11:11.",
      "You know you should call Eli.",
      "Instead, you open it.",
      "The room beyond is not a room. It is the same hallway, but darker, older, soaked in dust.",
      "Another version of you sits on the floor holding Eli’s coat.",
      "They look like they have not slept in years.",
      "When they see you, they do not seem surprised.",
      "\"You are early,\" they say.",
      "You ask where Eli is.",
      "The other you laughs once, but it breaks before it becomes sound.",
      "\"Which Eli?\"",
      "On the wall behind them are tally marks. Dozens. Hundreds.",
      "At the bottom, written in your handwriting:",
      "\"Do not let Eli know how much they remember.\"",
      "The other you crawls toward the door and grips your wrist.",
      "\"They are not the one who started this,\" they whisper.",
      "\"We are only catching up.\""
    ],
    choiceText: "Step Inside",
    quote: "Some doors do not open into rooms. They open into grief that learned to wait.",
    endingHint:
      "Before you can ask what Eli remembers, the other you is pulled backward into darkness.",
  },

  {
    id: 8,
    title: "The First Paradox",
    subtitle: "You tell Eli too much, too early.",
    traveler: "You",
    prop: "Unsent Message",
    clockMode: "warning",
    visualMode: "blue",
    fragmentType: "message",
    mainText: [
      "You are tired of lying to someone you keep losing.",
      "So you tell Eli everything.",
      "The first message. The crosswalk. The watch. The apartment. The train. The door. The version of yourself that looked older than grief.",
      "You expect Eli to think you are losing your mind.",
      "They do not.",
      "They go quiet in a way that scares you more than disbelief.",
      "\"What time?\" Eli asks.",
      "You blink.",
      "\"What time does it always happen?\"",
      "\"11:11 PM.\"",
      "Eli closes their eyes.",
      "For a moment, their face changes. Not older, exactly. Just heavier.",
      "Like a person briefly remembering the weight of a life they were not supposed to carry.",
      "\"How many times have you watched me die?\" they ask.",
      "Your throat locks.",
      "Before you can answer, your phone lights up with a new unsent draft.",
      "\"Do not answer that.\"",
      "The clock on the wall jumps from 4:16 PM to 11:11 PM.",
      "Eli reaches for you.",
      "\"Wait,\" they say. \"I know this part.\""
    ],
    choiceText: "Answer Eli",
    quote: "Truth can be a wound if it arrives before memory is ready.",
    endingHint:
      "The timeline forces a reset the moment Eli almost remembers too much.",
  },

  {
    id: 9,
    title: "The Room Full of Tomorrow",
    subtitle: "The future has been collecting your failures.",
    traveler: "You",
    prop: "Wall of Photos",
    clockMode: "normal",
    visualMode: "blue",
    fragmentType: "photo",
    mainText: [
      "The impossible room returns.",
      "This time, you do not find it by accident. The broken watch leads you there, ticking harder whenever you face the wrong direction.",
      "Behind the old door is a room covered in photographs.",
      "Not memories. Evidence.",
      "Eli at the crosswalk. Eli in the apartment. Eli on the train. Eli in the hospital you have not tried yet. Eli at a red station you have never seen.",
      "Each photo is labeled with a timeline number.",
      "Timeline 001.",
      "Timeline 002.",
      "Timeline 006.",
      "Timeline 012.",
      "Some photos show endings you remember. Some show failures you have not reached.",
      "On one wall, there are pictures of you.",
      "In some, you are alive.",
      "In others, Eli is holding your body.",
      "Your hands go cold.",
      "The final row has only two frames.",
      "Timeline 049 is filled with a photograph of Eli standing before a white door.",
      "Timeline 050 is empty.",
      "Under the empty frame, someone has written:",
      "\"This one is not yours.\""
    ],
    choiceText: "Touch The Last Photo",
    quote: "Tomorrow is not coming. It is waiting to see who pays for it.",
    endingHint:
      "Behind the empty Timeline 050 frame, you hear Eli crying from the other side of the wall.",
  },

  {
    id: 10,
    title: "Stop Saving Me",
    subtitle: "Eli’s voice comes from a future you have not reached.",
    traveler: "You",
    prop: "Broken Watch",
    clockMode: "frozen",
    visualMode: "blue",
    fragmentType: "audio",
    mainText: [
      "On the tenth morning, the watch will not open.",
      "You press the button until your thumb hurts. You whisper Eli’s name. You promise the empty room you will find a better way.",
      "At 11:11 AM, exactly twelve hours before the usual ending, the watch opens by itself.",
      "There is no photograph inside now.",
      "Only a small speaker hidden behind the cracked face.",
      "Static breathes through it.",
      "Then Eli’s voice begins.",
      "\"If you hear this, it means you started again.\"",
      "Their voice is not the Eli from this morning. It is thinner. Older. Exhausted by a grief you do not yet understand.",
      "\"I know you think love means trying one more time.\"",
      "\"I know you think if you find the right road, the right door, the right minute, you can bring me back.\"",
      "The recording breaks into static.",
      "When it returns, Eli is crying.",
      "\"But every time you save me, something else takes your place.\"",
      "\"Every time you refuse to let me go, another part of you disappears.\"",
      "\"Please.\"",
      "\"Stop saving me.\"",
      "You hold the watch so tightly the cracked glass cuts your palm.",
      "Eli whispers your name one last time.",
      "\"You were never supposed to be the one chasing me.\""
    ],
    choiceText: "Replay The Voice",
    quote: "The person you are trying to save is begging you to stop, and you still do not know why.",
    endingHint:
      "The recording ends with a second voice in the background. It is yours, dying in Eli’s arms.",
  },

  {
    id: 11,
    title: "The Timeline Tax",
    subtitle: "Every rescue takes something from you.",
    traveler: "You",
    prop: "Memory Fragment",
    clockMode: "normal",
    visualMode: "blue",
    fragmentType: "memory",
    mainText: [
      "You do not notice the first thing you lose.",
      "That is what makes it cruel.",
      "On the eleventh morning, Eli asks what song you want to play while making coffee.",
      "You smile automatically, because there has always been one song. The song Eli plays when they are happy. The song they played the first time you danced in the kitchen. The song you once hated until loving Eli made you love it too.",
      "But when you open your mouth, the title is gone.",
      "Not forgotten like a word on the tip of your tongue.",
      "Gone like it was never written inside you.",
      "Eli watches your face change.",
      "\"You forgot it,\" they say softly.",
      "You laugh too quickly. You say you are tired. You say the loops are making your head strange.",
      "But later, alone in the bathroom, you try to hum the melody.",
      "Nothing comes.",
      "The watch grows warm in your palm.",
      "A message appears across the cracked glass:",
      "\"EVERY RESCUE COSTS A MEMORY.\"",
      "You scroll through your phone, desperate to prove the song existed.",
      "The playlist is there.",
      "The track number is there.",
      "The file is empty.",
      "Eli knocks on the door.",
      "\"Are you okay?\"",
      "You look at your reflection and realize you can still remember exactly how Eli dies.",
      "You just cannot remember how they sounded when they were alive."
    ],
    choiceText: "Keep Going",
    quote: "You are saving a life by losing the reasons you loved it.",
    endingHint:
      "A photo of Eli laughing remains on your phone, but the audio attached to it is silent.",
  },

  {
    id: 12,
    title: "The Hospital Without Names",
    subtitle: "Even safety cannot hold someone who does not belong.",
    traveler: "You",
    prop: "Hospital Bracelet",
    clockMode: "warning",
    visualMode: "blue",
    fragmentType: "photo",
    mainText: [
      "You choose the most reasonable place left.",
      "A hospital has lights that never sleep. Cameras in the halls. Doors that lock. People trained to save bodies when the world tries to take them.",
      "You bring Eli there before sunset.",
      "You say it is for a checkup. Eli knows you are lying but sits beside you anyway.",
      "The waiting room smells like antiseptic and old fear.",
      "For a while, everything feels almost normal.",
      "A nurse wraps a bracelet around Eli’s wrist.",
      "The bracelet prints blank.",
      "The nurse frowns, tries again, then again.",
      "Blank.",
      "At 10:58 PM, every patient chart in the hospital loses its name.",
      "At 11:04 PM, the elevators open and close by themselves.",
      "At 11:08 PM, the lights above Eli’s bed begin blinking in a rhythm that sounds like a countdown.",
      "The doctor returns with an expression too empty to be human.",
      "\"This patient does not belong to this timeline,\" he says.",
      "You grab Eli’s hand.",
      "Their skin is cold.",
      "\"Don’t let them take me,\" Eli whispers.",
      "At 11:11 PM, the heart monitor screams once.",
      "Then becomes a flat line.",
      "But Eli is still sitting up.",
      "Still looking at you.",
      "The line on the monitor is not Eli’s.",
      "It is yours."
    ],
    choiceText: "Grab Eli’s Hand",
    quote: "A safe room means nothing if time itself wants someone gone.",
    endingHint:
      "Eli’s hospital bracelet finally prints a name. It prints yours.",
  },

  {
    id: 13,
    title: "The Photo That Fades First",
    subtitle: "The world begins erasing proof that Eli existed.",
    traveler: "You",
    prop: "Fading Photo",
    clockMode: "normal",
    visualMode: "blue",
    fragmentType: "photo",
    mainText: [
      "You start collecting proof.",
      "Photos. Screenshots. Receipts. Voice memos. Anything that can survive a reset better than your memory can.",
      "You print your favorite photo of Eli and tape it above your desk.",
      "It is from a day before any of this began.",
      "Eli is standing outside a small café, holding two paper cups, pretending not to smile because you told them not to move.",
      "You used to remember that day perfectly.",
      "The rain had stopped. Eli had stolen your scarf. You had said something stupid and made them laugh.",
      "Now the details are full of holes.",
      "At first, only the color fades.",
      "Then the café sign disappears.",
      "Then the cup in Eli’s hand becomes a pale blur.",
      "Then Eli’s face begins to vanish from the paper.",
      "You press your palm against the photo like you can hold the ink in place.",
      "\"Stay,\" you whisper.",
      "The picture keeps fading.",
      "By 11:11 PM, Eli is gone from the photo.",
      "Only you remain, smiling at an empty space.",
      "On the back, a sentence appears in thin gray letters:",
      "\"ONE OF YOU HAS ALREADY BEEN ERASED.\"",
      "You flip the photo again.",
      "Your hand is no longer holding anyone’s."
    ],
    choiceText: "Save The Photo",
    quote: "Some memories do not fade. They are taken.",
    endingHint:
      "The café in the photo no longer exists on the map, but its address now points to the red station.",
  },

  {
    id: 14,
    title: "Seven Minutes Earlier",
    subtitle: "The watch gives you less time than before.",
    traveler: "You",
    prop: "Broken Watch",
    clockMode: "warning",
    visualMode: "blue",
    fragmentType: "watch",
    mainText: [
      "This reset is wrong from the first breath.",
      "You do not wake up at 7:00 AM.",
      "You wake up running.",
      "Your lungs are burning. Your phone is in your hand. The broken watch is screaming against your wrist.",
      "11:04 PM.",
      "Seven minutes.",
      "The city around you is already bent toward the ending.",
      "Street signs point in impossible directions. Traffic lights blink 11:11 in red. Every reflection shows Eli standing somewhere behind you.",
      "You call Eli.",
      "No answer.",
      "You try the apartment.",
      "Locked.",
      "You try the crosswalk.",
      "Empty.",
      "You try the train station.",
      "Closed.",
      "At 11:08 PM, Eli finally calls.",
      "\"Do not come closer,\" they say.",
      "Their voice is shaking, but not with fear.",
      "With recognition.",
      "\"I think this is the one where you die.\"",
      "You run harder.",
      "At 11:10 PM, you see Eli across the street.",
      "They are crying.",
      "You reach for them.",
      "One minute left.",
      "Eli steps backward and shakes their head.",
      "\"Not this time.\"",
      "At 11:11 PM, Eli pushes you away from nothing you can see.",
      "Something invisible takes their place."
    ],
    choiceText: "Try Another Route",
    quote: "Sometimes the universe gives you time only to prove it is not enough.",
    endingHint:
      "As the reset begins, you hear Eli say, \"I knew where it would come from.\"",
  },

  {
    id: 15,
    title: "The Stranger at the Crosswalk",
    subtitle: "Someone saves you before Eli can die.",
    traveler: "You",
    prop: "Watch Shard",
    clockMode: "normal",
    visualMode: "blue",
    fragmentType: "watch",
    mainText: [
      "You return to the crosswalk because grief keeps circling its first wound.",
      "This time, you do not bring Eli.",
      "You tell yourself if Eli is far away, the timeline cannot trade them for you.",
      "The city is quiet. Too quiet.",
      "At 11:09 PM, the pedestrian light turns white even though no button was pressed.",
      "At 11:10 PM, your phone displays an incoming call from Eli.",
      "You do not answer.",
      "You stare at the empty road and wait for the universe to show its hand.",
      "Then headlights appear from a street that has been blocked for construction all week.",
      "The car is not coming for Eli.",
      "It is coming for you.",
      "Your body freezes.",
      "A stranger grabs your wrist and pulls you backward so violently your shoulder burns.",
      "The car passes through the place where your chest was a second ago.",
      "When you turn, the stranger is already walking away.",
      "Same height as Eli.",
      "Same coat.",
      "Same way of touching your wrist like they are afraid you might vanish.",
      "You chase them through the rain.",
      "\"Wait!\"",
      "The stranger stops beneath a broken streetlight.",
      "For half a second, they turn.",
      "You do not see their face.",
      "You see the watch in their hand.",
      "It is more broken than yours.",
      "A shard falls to the pavement.",
      "By the time you pick it up, the stranger is gone."
    ],
    choiceText: "Chase The Stranger",
    quote: "The person you are saving may have saved you first.",
    endingHint:
      "The watch shard is engraved with Eli’s initial.",
  },

  {
    id: 16,
    title: "The Notebook of Failed Worlds",
    subtitle: "Another traveler has been keeping records.",
    traveler: "You",
    prop: "Failed Worlds Notebook",
    clockMode: "normal",
    visualMode: "blue",
    fragmentType: "letter",
    mainText: [
      "The watch shard leads you to a storage locker you have never rented.",
      "The key is inside your coat pocket before you know to look for it.",
      "Inside the locker: a box, a train ticket, three dead phones, and a black notebook wrapped in plastic.",
      "You open the notebook expecting your own handwriting.",
      "Some pages are yours.",
      "Timeline 003: Keep Eli home. Failed.",
      "Timeline 006: Leave by train. Failed.",
      "Timeline 014: Seven-minute reset. Failed.",
      "Then the handwriting changes.",
      "Softer. Smaller. Familiar in a way that makes your chest hurt.",
      "Timeline 021: They almost saw me at the crosswalk.",
      "Timeline 044: They died before I reached the hospital.",
      "Timeline 087: I saved them, but they forgot my name.",
      "You stop breathing.",
      "These are not your timelines.",
      "Someone else has been writing failures you never lived.",
      "On the next page, the ink is darker.",
      "\"They keep trying to save me.\"",
      "\"They don’t know I started first.\"",
      "At the bottom of the page is one letter.",
      "E."
    ],
    choiceText: "Read More",
    quote: "You were never the only one fighting time.",
    endingHint:
      "The next page contains a list titled: Ways to keep them alive without letting them know.",
  },

  {
    id: 17,
    title: "The Song From Another Life",
    subtitle: "A song that only exists inside broken timelines.",
    traveler: "You",
    prop: "Unknown Song",
    clockMode: "normal",
    visualMode: "blue",
    fragmentType: "audio",
    mainText: [
      "The missing song returns before you remember its name.",
      "Eli hums it while washing a cup.",
      "A soft melody. Three rising notes. A pause. Then something like a goodbye hidden inside a lullaby.",
      "Your entire body reacts before your mind does.",
      "\"Where did you learn that?\" you ask.",
      "Eli looks down at the sink.",
      "\"I don’t know.\"",
      "You record them humming it.",
      "The file saves successfully.",
      "For once, something stays.",
      "You upload the audio. No match.",
      "You search the lyrics. No result.",
      "You hum it into every music recognition app you can find.",
      "Nothing.",
      "That night, Eli sings under their breath while pretending to sleep.",
      "The words are different now.",
      "\"If I disappear, remember the life I gave back to you.\"",
      "You sit beside the bed and listen until dawn.",
      "At 7:00 AM, the recording file changes its name.",
      "goodbye_107.mp3.",
      "You do not know what 107 means yet.",
      "But the number makes Eli cry when they see it."
    ],
    choiceText: "Record The Song",
    quote: "Some songs are not written. They survive.",
    endingHint:
      "When you play the audio backward, Eli’s voice says, \"I have watched you die before.\"",
  },

  {
    id: 18,
    title: "The World Where You Never Met",
    subtitle: "You try to erase the beginning.",
    traveler: "You",
    prop: "First Meeting Place",
    clockMode: "normal",
    visualMode: "blue",
    fragmentType: "memory",
    mainText: [
      "You decide love is the first mistake.",
      "Not because you regret Eli.",
      "Because you cannot bear the thought that being loved by you is what put them in the path of time.",
      "So you go back further.",
      "Before the message.",
      "Before the watch.",
      "Before the coffee.",
      "Before the first inside joke, the first shared umbrella, the first time Eli said your name like it was safe.",
      "The day you met, you do not enter the café.",
      "You cross the street early. You ignore the rain. You let the door close before Eli arrives.",
      "The universe feels quieter without the meeting.",
      "Emptier.",
      "You spend the entire day avoiding every place where your life once touched theirs.",
      "At 11:11 PM, you stand alone under a streetlight and wait for nothing to happen.",
      "Then someone runs toward you.",
      "Eli.",
      "Out of breath. Soaked in rain. A stranger again.",
      "\"I don’t know you,\" they say.",
      "Behind them, a car loses control.",
      "Eli pushes you out of the way before you can move.",
      "The white light takes them.",
      "Even in a world where you never met, Eli finds a way to save you first."
    ],
    choiceText: "Step Toward Eli",
    quote: "Love does not always begin with memory.",
    endingHint:
      "As the world resets, stranger-Eli whispers, \"I think I came here for you.\"",
  },

  {
    id: 19,
    title: "The Empty Seat Beside You",
    subtitle: "The world remembers a date you lost.",
    traveler: "You",
    prop: "Movie Ticket",
    clockMode: "normal",
    visualMode: "blue",
    fragmentType: "ticket",
    mainText: [
      "You wake in a movie theater.",
      "No alarm. No bedroom. No morning light.",
      "Just red seats, stale popcorn, and the flicker of a screen showing nothing but static.",
      "The seat beside you is empty.",
      "But the popcorn there is still warm.",
      "Two tickets are in your hand.",
      "One has your name.",
      "The other has Eli’s name, fading one letter at a time.",
      "You do not remember buying these tickets.",
      "You do not remember this date.",
      "But your body remembers where Eli’s shoulder should be against yours.",
      "The screen brightens.",
      "A film begins playing.",
      "Not a movie.",
      "A memory.",
      "You and Eli sitting in this same theater, years ago, whispering jokes through a terrible film.",
      "Eli reaches over in the memory and steals your popcorn.",
      "You laugh.",
      "In the present, you cannot remember the sound.",
      "The Eli on the screen suddenly turns away from memory and looks directly at you.",
      "\"You keep saving my ending,\" they say from the screen.",
      "\"But you are losing all the middle parts.\"",
      "The empty seat beside you folds itself up.",
      "The ticket with Eli’s name turns blank."
    ],
    choiceText: "Watch The Screen",
    quote: "An empty seat can be louder than a scream.",
    endingHint:
      "The film ends with a frame you have never seen: Eli sitting alone, watching your seat disappear.",
  },

  {
    id: 20,
    title: "The First Time You Gave Up",
    subtitle: "You stop running. The world punishes the memory.",
    traveler: "You",
    prop: "Silent Watch",
    clockMode: "collapse",
    visualMode: "blue",
    fragmentType: "memory",
    mainText: [
      "You are exhausted in a way sleep cannot repair.",
      "Twenty timelines have taught you the shape of failure from every angle.",
      "Run, and Eli dies.",
      "Stay, and Eli dies.",
      "Leave, and Eli dies.",
      "Forget the beginning, and Eli still finds you.",
      "For the first time, you decide not to move.",
      "No phone calls.",
      "No train tickets.",
      "No hospital.",
      "No desperate map of impossible roads.",
      "You place the broken watch on the table and sit across from Eli.",
      "\"I’m tired,\" you admit.",
      "Eli reaches across the table.",
      "\"Then rest.\"",
      "At 11:11 PM, nothing happens.",
      "No white light.",
      "No scream.",
      "No reset.",
      "For one beautiful second, you think surrender has saved you both.",
      "Then Eli’s name disappears from your phone.",
      "Their contact photo becomes a gray circle.",
      "The messages vanish.",
      "The photos empty themselves.",
      "The world does not take Eli’s body this time.",
      "It takes the fact that Eli ever existed.",
      "You run outside and ask strangers if they remember Eli.",
      "No one does.",
      "You check the café. The movie theater. The apartment. The crosswalk.",
      "Nothing.",
      "When you return home, the chair across from you is empty.",
      "The watch on the table displays a new message:",
      "\"TIMELINE 020: MEMORY COLLAPSE.\"",
      "You realize giving up is not the same as letting go.",
      "Giving up only leaves you alone with a world that never knew what you lost."
    ],
    choiceText: "Remember Eli",
    quote: "Giving up is not the same as letting go.",
    endingHint:
      "Only one thing still remembers Eli: the second watch shard hidden under your skin.",
  },

  {
    id: 21,
    title: "A Handwriting You Know",
    subtitle: "Eli has written from beyond your failures.",
    traveler: "You",
    prop: "Failed Worlds Notebook",
    clockMode: "normal",
    visualMode: "blue",
    fragmentType: "letter",
    mainText: [
      "The notebook does not leave with the reset.",
      "That is the first miracle of Timeline 021.",
      "It sits on your desk in the morning, damp from rain that has not fallen yet, open to a page you swear was blank before.",
      "You compare the handwriting to an old birthday card Eli gave you years ago.",
      "Same tilted letters.",
      "Same pressure on the last stroke of your name.",
      "Same tiny star Eli draws instead of a period when they are nervous.",
      "The page is dated after the night Eli died.",
      "Then another page.",
      "And another.",
      "Some entries were written in places you have not reached yet.",
      "A hospital without names.",
      "A red station.",
      "A white room between seconds.",
      "You read until your hands go numb.",
      "One sentence stops everything inside you.",
      "\"If they find this, I failed to protect them again.\"",
      "Again.",
      "The word is heavier than death.",
      "You turn the page.",
      "A fresh line appears while you are looking at it.",
      "\"They still think I am the one being saved.\"",
      "The ink is wet.",
      "Eli is writing from somewhere the current timeline has not allowed you to enter."
    ],
    choiceText: "Trace The Ink",
    quote: "The handwriting of the dead can still arrive early.",
    endingHint:
      "A new page appears with only three words: Original Timeline First.",
  },

  {
    id: 22,
    title: "The Version of You That Died",
    subtitle: "The original ending was never Eli’s death.",
    traveler: "You",
    prop: "Original Timeline",
    clockMode: "frozen",
    visualMode: "red",
    fragmentType: "memory",
    mainText: [
      "The words Original Timeline First burn through the notebook page.",
      "The paper opens like a door.",
      "You fall into rain.",
      "Same street.",
      "Same white light.",
      "Same broken second before everything is taken.",
      "But this time, the scene is wrong.",
      "Eli is not in danger.",
      "You are.",
      "You watch a version of yourself step into the road, distracted by a message you never get to read.",
      "A car appears from nowhere.",
      "Eli sees it first.",
      "They could stay on the sidewalk.",
      "They could survive.",
      "Instead, Eli runs.",
      "They push you away with both hands.",
      "The white light hits you anyway.",
      "Not Eli.",
      "You.",
      "The body on the pavement is yours.",
      "Eli collapses beside it and screams your name with a sound you have never heard from them in any timeline.",
      "Then Eli sees the broken watch lying beside your hand.",
      "They pick it up.",
      "Their thumb finds the side button.",
      "The hands move backward for the first time.",
      "The rain lifts into the sky.",
      "The world rewinds.",
      "Eli whispers, \"No. Not this ending.\""
    ],
    choiceText: "Watch The Original",
    quote: "Before you tried to save Eli, Eli broke time to save you.",
    endingHint:
      "The original body on the pavement was yours, and Eli was the first person to reset the world.",
  },

  {
    id: 23,
    title: "The Message Under the Floor",
    subtitle: "Eli hid the truth where only grief would search.",
    traveler: "You",
    prop: "Hidden Recorder",
    clockMode: "normal",
    visualMode: "blue",
    fragmentType: "audio",
    mainText: [
      "The original memory leaves you shaking for hours.",
      "You return to the apartment because the notebook tells you to.",
      "Under the bed, beneath a loose floorboard you never noticed, there is a small recorder wrapped in Eli’s scarf.",
      "The scarf still smells faintly like rain and coffee.",
      "You press play.",
      "Static opens first.",
      "Then Eli’s voice.",
      "Not the voice from your current morning.",
      "This Eli sounds like someone who has spent too many lives trying not to break.",
      "\"I found a way to move through time too.\"",
      "\"I only wanted to save you once.\"",
      "\"One reset. One impossible little miracle. That was all I asked for.\"",
      "The recorder clicks.",
      "When Eli continues, they are crying.",
      "\"But time does not give gifts. It makes trades.\"",
      "\"The first time I saved you, it asked for my future.\"",
      "\"The second time, it asked for your memory of my laugh.\"",
      "\"The third time, it asked whether I was willing to become the one you would keep losing.\"",
      "You sit on the floor with the recorder in both hands.",
      "In the background of the audio, you hear yourself crying.",
      "You hear Eli whisper to that version of you:",
      "\"Please live long enough to hate me for this.\""
    ],
    choiceText: "Play The Recorder",
    quote: "A secret can survive beneath the floor longer than a body can survive time.",
    endingHint:
      "The recorder contains one final file labeled: DO NOT PLAY BEFORE TIMELINE 039.",
  },

  {
    id: 24,
    title: "The Timeline Where Eli Lied",
    subtitle: "Eli’s dreams are not dreams.",
    traveler: "You",
    prop: "Dream Journal",
    clockMode: "normal",
    visualMode: "blue",
    fragmentType: "letter",
    mainText: [
      "Eli has been lying badly.",
      "You notice it in the way they stop talking when clocks appear in movies.",
      "In the way they refuse to stand near crosswalks.",
      "In the way their hand covers their wrist whenever the watch ticks.",
      "You find the dream journal in their bag by accident.",
      "The cover says Dreams, but the pages read like reports from places you have not survived yet.",
      "A hospital where every name disappears.",
      "A red station where no trains arrive.",
      "A white room where one second lasts long enough to say goodbye.",
      "A house that remembers two different griefs.",
      "A line appears again and again in Eli’s handwriting:",
      "\"Do not let them know I remember.\"",
      "When Eli finds you reading, they do not get angry.",
      "They look relieved.",
      "Like the lie was heavier than being caught.",
      "\"I was going to tell you,\" they say.",
      "\"When?\"",
      "Eli smiles weakly.",
      "\"In a timeline where telling you did not get you killed.\"",
      "The dream journal falls open by itself.",
      "A new entry writes across the page:",
      "\"Timeline 024: confession risk increasing.\"",
      "Then another sentence appears below it.",
      "\"Traveler Eli memory leak detected.\""
    ],
    choiceText: "Ask Eli Again",
    quote: "A lie told to protect you still cuts like truth.",
    endingHint:
      "A thin crack of blue light appears on Eli’s wrist, shaped like the hands of a watch.",
  },

  {
    id: 25,
    title: "The Red Station",
    subtitle: "A station between endings.",
    traveler: "You",
    prop: "Red Station Ticket",
    clockMode: "frozen",
    visualMode: "red",
    fragmentType: "ticket",
    mainText: [
      "At 11:11 PM, the apartment door opens into a train station.",
      "Not the city station.",
      "Not any station built for the living.",
      "Everything is red.",
      "Red tiles. Red lights. Red fog moving along the floor like something breathing.",
      "Thousands of clocks hang from the ceiling, all frozen at 11:11 PM.",
      "Eli goes pale.",
      "\"I know this place,\" they whisper.",
      "You turn to them.",
      "\"From a dream?\"",
      "Eli does not answer.",
      "A ticket appears in your hand.",
      "Passenger: You.",
      "Destination: Original Debt.",
      "A second ticket appears in Eli’s hand.",
      "Passenger: Eli.",
      "Destination: Substitute Ending.",
      "There are no trains on the tracks.",
      "Only doors.",
      "Each platform door shows a different version of the two of you losing each other.",
      "The speaker system crackles awake.",
      "\"Two travelers cannot leave the same timeline together.\"",
      "Every clock ticks once.",
      "The sound is so loud it feels like a verdict.",
      "Eli grips your sleeve.",
      "\"Do not choose a door yet,\" they say.",
      "\"That is how it separates us.\""
    ],
    choiceText: "Enter The Platform",
    quote: "Some stations are built for people who cannot arrive together.",
    endingHint:
      "Behind a wall of broken clocks, a fourth rule waits under dried blood.",
  },

  {
    id: 26,
    title: "The Rules Written in Blood",
    subtitle: "Time finally explains its cruelty.",
    traveler: "You",
    prop: "Timeline Rules",
    clockMode: "warning",
    visualMode: "red",
    fragmentType: "museum",
    mainText: [
      "The red station does not have maps.",
      "It has rules.",
      "They appear on the wall one by one, written in a dark red that does not dry.",
      "Rule One:",
      "\"One life may be returned.\"",
      "Rule Two:",
      "\"One memory must be paid.\"",
      "Rule Three:",
      "\"Two travelers cannot keep the same ending.\"",
      "You read them again and again, trying to find a loophole in grammar.",
      "Eli does not read them.",
      "Eli stares at the section where a fourth rule has been covered in blood.",
      "You reach toward it.",
      "Eli grabs your hand.",
      "\"Don’t.\"",
      "\"Why?\"",
      "\"Because I wiped it away once.\"",
      "The station lights dim.",
      "Your fingers touch the blood anyway.",
      "It peels from the wall like old paint.",
      "The fourth rule appears beneath it.",
      "\"The one who remembers most must choose last.\"",
      "Eli closes their eyes.",
      "You understand too late why they did not want you to read it.",
      "Eli remembers more.",
      "Eli has always remembered more."
    ],
    choiceText: "Wipe The Wall",
    quote: "A rule written in blood has already been broken.",
    endingHint:
      "The fourth rule reveals why Eli keeps arriving before you.",
  },

  {
    id: 27,
    title: "The Life You Borrowed",
    subtitle: "Your survival has Eli’s fingerprints all over it.",
    traveler: "You",
    prop: "Borrowed Life",
    clockMode: "normal",
    visualMode: "blue",
    fragmentType: "memory",
    mainText: [
      "The station opens into a room made of moving memories.",
      "At first, you think they are yours.",
      "Then you see Eli in every one.",
      "Eli missing a train so you could catch it.",
      "Eli stepping into smoke so you would wake up outside the fire.",
      "Eli closing a door from the wrong side.",
      "Eli pressing the watch while your body lies still on a hospital floor.",
      "Memory after memory shows your survival from angles you never saw.",
      "You called it luck.",
      "A delayed bus.",
      "A phone call at the right second.",
      "A stranger pulling you back from the curb.",
      "A door that jammed before you could walk through it.",
      "But luck has Eli’s hands.",
      "Luck has Eli’s coat.",
      "Luck has Eli whispering, \"Don’t tell them. Let them live.\"",
      "You step backward.",
      "The room keeps showing more.",
      "Not ten times.",
      "Not twenty.",
      "More than the wall can count.",
      "Every version of your ordinary life is built on something Eli gave up quietly.",
      "And you never knew enough to say thank you."
    ],
    choiceText: "Keep Watching",
    quote: "You called it luck because Eli never let you see the cost.",
    endingHint:
      "The final memory shows Eli carving your name into the back of their watch.",
  },

  {
    id: 28,
    title: "Do Not Follow Me",
    subtitle: "Eli runs because your love is becoming another loop.",
    traveler: "You",
    prop: "Eli’s Note",
    clockMode: "warning",
    visualMode: "blue",
    fragmentType: "letter",
    mainText: [
      "Eli disappears before sunset.",
      "No call.",
      "No final message.",
      "No dramatic goodbye.",
      "Just an empty chair, a cooling cup of coffee, and a note on the kitchen table.",
      "\"If you love me, don’t follow me this time.\"",
      "You read it once.",
      "Then again.",
      "Then a third time, as if the sentence might become less impossible.",
      "Of course you follow.",
      "Love has become a reflex stronger than reason.",
      "The watch screams when you leave the apartment.",
      "Every streetlight turns toward you like an eye.",
      "The closer you get to Eli, the more the world tears.",
      "Windows show timelines that are not yours.",
      "A child points at you and says, \"That person is breaking the ending.\"",
      "At 11:09 PM, you find Eli at the red station entrance.",
      "They are holding both tickets.",
      "\"I told you not to come,\" Eli says.",
      "\"You knew I would.\"",
      "\"That’s the problem.\"",
      "The ground splits between you.",
      "Eli’s voice shakes.",
      "\"Every time you follow me, time learns how to hurt you better.\"",
      "You reach anyway.",
      "The moment your fingers touch, the timeline tears open."
    ],
    choiceText: "Follow Eli",
    quote: "Sometimes chasing someone is how you lose them faster.",
    endingHint:
      "Inside the tear, you see a house that remembers two versions of your grief.",
  },

  {
    id: 29,
    title: "The House That Remembers Both of You",
    subtitle: "Two lives haunt the same home.",
    traveler: "You",
    prop: "Memory House",
    clockMode: "normal",
    visualMode: "blue",
    fragmentType: "memory",
    mainText: [
      "The tear drops you into a house you have never seen but somehow know how to walk through.",
      "Two sets of keys hang by the door.",
      "Two coats on the rack.",
      "Two coffee cups in the sink.",
      "But every room tells two different stories.",
      "In one version of the bedroom, you slept alone after losing Eli.",
      "In another, Eli slept alone after losing you.",
      "The bedsheets change when you blink.",
      "Your side becomes Eli’s side.",
      "Eli’s absence becomes yours.",
      "In the bathroom, two toothbrushes trade places.",
      "In the kitchen, a grocery list is written first in your handwriting, then in Eli’s.",
      "The house is not haunted by ghosts.",
      "It is haunted by outcomes.",
      "You find a wall covered in notes.",
      "\"They were not the only one grieving.\"",
      "\"They were not the only one waiting.\"",
      "\"They were not the only one trying to make a home out of what survived.\"",
      "Eli stands in the doorway behind you.",
      "\"I lived here too,\" they say.",
      "\"After you died.\"",
      "The house exhales.",
      "The floorboards open beneath the bed.",
      "Something metallic shines below."
    ],
    choiceText: "Touch The Wall",
    quote: "A home can remember every version of heartbreak.",
    endingHint:
      "Beneath the house, Eli’s second watch waits in a box marked For the one who keeps forgetting.",
  },

  {
    id: 30,
    title: "The Second Watch",
    subtitle: "Eli’s watch is older than yours.",
    traveler: "You",
    prop: "Eli’s Watch",
    clockMode: "frozen",
    visualMode: "blue",
    fragmentType: "watch",
    mainText: [
      "The box under the floor is wrapped in a scarf you remember and do not remember.",
      "Eli kneels beside you but does not touch it.",
      "\"You should open it,\" they say.",
      "\"Why not you?\"",
      "Eli looks at the floor.",
      "\"Because I already did.\"",
      "Inside is a second broken watch.",
      "Older than yours.",
      "More damaged.",
      "The glass is cracked in three directions. The strap is burned. The hinge is stained with something darker than rust.",
      "You lift it carefully.",
      "It is warm.",
      "Not like metal left in the sun.",
      "Like something alive has been holding its breath.",
      "On the back, carved by hand, are words you have seen before but never understood:",
      "\"In every timeline, I chose you.\"",
      "Your watch begins to tick.",
      "Eli’s watch answers.",
      "Two sounds.",
      "Two heartbeats.",
      "Two travelers.",
      "The room dissolves around you.",
      "For one second, you see every reset as two circles overlapping.",
      "Your circle began with losing Eli.",
      "Eli’s circle began with losing you.",
      "Neither of you has been moving forward.",
      "You have been orbiting the same wound from opposite sides.",
      "When both watches touch, the air splits open.",
      "A museum appears beyond the white crack.",
      "Above its entrance, letters glow in red and blue:",
      "\"THE TIMELINE MUSEUM.\"",
      "Eli takes your hand.",
      "\"This is where all failed worlds go,\" they whisper.",
      "\"And where the truth stops pretending to be mercy.\""
    ],
    choiceText: "Join The Watches",
    quote: "The second watch proves the first sacrifice was never yours.",
    endingHint:
      "When both watches touch, the Timeline Museum opens.",
  },

  {
    id: 31,
    title: "The Timeline Museum",
    subtitle: "Every failed world has been preserved.",
    traveler: "You",
    prop: "Timeline Museum",
    clockMode: "frozen",
    visualMode: "red",
    fragmentType: "museum",
    universeEasterEgg: {
      linkedSeries: "The Red Eye Files: Final Goodbye",
      object: "A faded photograph stitched with a red thread.",
      label: "Some goodbyes happen in other rooms.",
      meaning:
        "A quiet universe-level connection to the Red Eye Files, hinting that the Archive and Museum belong to the same emotional universe.",
    },
    mainText: [
      "The Timeline Museum is silent.",
      "Each glass case contains one failed world.",
      "You see Eli gone. You see yourself gone. You see cities frozen at 11:11 PM.",
      "In one corner, there is a faded photograph stitched with a red thread.",
      "The small label reads: Some goodbyes happen in other rooms."
    ],
    choiceText: "Enter The Original Exhibit",
    quote: "Every universe keeps its grief somewhere.",
    endingHint: "The largest exhibit is labeled: Original Timeline — You Died.",
  },

  {
    id: 32,
    title: "The Birthday You Forgot",
    subtitle: "You remember Eli’s death better than Eli’s life.",
    traveler: "You",
    prop: "Birthday Candle",
    clockMode: "normal",
    visualMode: "blue",
    fragmentType: "memory",
    mainText: [
      "Inside the museum, you find a birthday cake with one candle burning.",
      "You know the exact second Eli dies.",
      "You know the sound of the watch before every reset.",
      "But you cannot remember Eli’s birthday.",
      "Eli asks, \"You remember how I die. Do you still remember how I lived?\""
    ],
    choiceText: "Remember Eli’s Life",
    quote: "Obsession remembers the wound. Love remembers the person.",
    endingHint: "The candle melts into the shape of 11:11.",
  },

  {
    id: 33,
    title: "The World Where Eli Stayed",
    subtitle: "You finally save Eli, but the cost moves to you.",
    traveler: "You",
    prop: "Borrowed Ending",
    clockMode: "normal",
    visualMode: "blue",
    fragmentType: "memory",
    mainText: [
      "For the first time, Eli stays.",
      "No accident arrives. No clock breaks. No white light takes them.",
      "You sit together in a quiet kitchen, stunned by peace.",
      "Then your fingers become transparent around the coffee cup.",
      "Eli sees it and does not look surprised. Only heartbroken."
    ],
    choiceText: "Hide Your Hand",
    quote: "A saved life can still be borrowed from someone else.",
    endingHint: "Eli whispers: This is why I kept leaving.",
  },

  {
    id: 34,
    title: "A Perfect Day, Almost",
    subtitle: "The day Eli wanted to give you.",
    traveler: "You",
    prop: "Two Coffees",
    clockMode: "normal",
    visualMode: "orange",
    fragmentType: "photo",
    mainText: [
      "There is no chase today.",
      "Only coffee, a walk through the city, an old song, and Eli’s hand in yours.",
      "You almost believe this is victory.",
      "At sunset, Eli looks at the sky and says:",
      "\"This is the day I kept trying to give you.\""
    ],
    choiceText: "Stay In The Day",
    quote: "A perfect day can hurt more than a terrible one.",
    endingHint: "The sun stops moving.",
  },

  {
    id: 35,
    title: "The Cost of Staying",
    subtitle: "The world cannot survive a stolen ending.",
    traveler: "You",
    prop: "Frozen Sky",
    clockMode: "collapse",
    visualMode: "orange",
    fragmentType: "memory",
    mainText: [
      "Eli is alive, but the world is dying.",
      "People walk without shadows.",
      "The clouds repeat the same shape.",
      "Every clock in the city becomes 11:11 PM.",
      "The timeline core displays: A borrowed ending cannot hold."
    ],
    choiceText: "Find The Core",
    quote: "Keeping someone can become another way of destroying them.",
    endingHint: "A white door appears at the center of the city.",
  },

  {
    id: 36,
    title: "The Letter From Future Eli",
    subtitle: "Eli tells you what they were truly saving.",
    traveler: "You",
    prop: "Future Letter",
    clockMode: "normal",
    visualMode: "blue",
    fragmentType: "letter",
    mainText: [
      "Behind the white door, you find a letter addressed to you.",
      "Eli’s handwriting trembles across the page.",
      "\"You thought you were saving me.\"",
      "\"I was saving the version of you who still knew how to love.\"",
      "You realize the loops have not only threatened Eli. They have been changing you."
    ],
    choiceText: "Open Memory 000",
    quote: "I was saving the version of you who still knew how to love.",
    endingHint: "The back of the letter says: Open Memory 000.",
  },

  {
    id: 37,
    title: "The Memory You Must Not Open",
    subtitle: "Truth requires your final safety.",
    traveler: "You",
    prop: "Memory 000",
    clockMode: "warning",
    visualMode: "blue",
    fragmentType: "memory",
    mainText: [
      "A warning appears before Memory 000 opens.",
      "If you continue, you will learn the original truth.",
      "But you will lose one final reset.",
      "You press your hand to the broken watch.",
      "The memory opens."
    ],
    choiceText: "Open Memory 000",
    quote: "Some truths cost the last chance to avoid them.",
    endingHint: "You return to the first 11:11 PM.",
  },

  {
    id: 38,
    title: "The Day You Were Supposed to Die",
    subtitle: "The original death was yours.",
    traveler: "You",
    prop: "Original Street",
    clockMode: "frozen",
    visualMode: "red",
    fragmentType: "memory",
    mainText: [
      "You see the original timeline.",
      "At 11:11 PM, the car is coming for you.",
      "Eli is safe. Eli could leave.",
      "Instead, Eli turns back, pushes you away, and takes your place in the light.",
      "Except in this first version, Eli survives. You do not."
    ],
    choiceText: "Watch Eli Reset Time",
    quote: "Before you tried to save Eli, Eli broke time to save you.",
    endingHint: "Eli’s watch begins moving for the first time.",
  },

  {
    id: 39,
    title: "The First Sacrifice",
    subtitle: "You are Eli now.",
    traveler: "Eli",
    prop: "Eli’s Watch",
    clockMode: "frozen",
    visualMode: "reversed",
    fragmentType: "watch",
    specialMode: "eliPerspective",
    mainText: [
      "The screen reverses.",
      "The colors shift from cold blue to warm orange.",
      "The button no longer says Save Eli.",
      "It says Save You.",
      "You are Eli. You remember every version of the person you love dying in front of you."
    ],
    choiceText: "Restart As Eli",
    quote: "This is the 107th time I watch you die. I’m not letting go yet.",
    endingHint: "Eli restarts the world and loses the memory of your first confession.",
  },

  {
    id: 40,
    title: "The Promise You Never Heard",
    subtitle: "Eli made a vow at your grave.",
    traveler: "Eli",
    prop: "Grave Memory",
    clockMode: "warning",
    visualMode: "orange",
    fragmentType: "memory",
    mainText: [
      "Still inside Eli’s memory, you stand in the rain beside your own grave.",
      "Eli’s hands are shaking around the watch.",
      "They whisper to the stone:",
      "\"I will break every timeline before I let this be the last one.\"",
      "The watch answers."
    ],
    choiceText: "Break The Timeline",
    quote: "I will break every timeline before I let this be the last one.",
    endingHint: "The system displays: Timeline 040 — Both Travelers Active.",
  },

  {
    id: 41,
    title: "Two Travelers, One Ending",
    subtitle: "Both of you were trying. Both of you were losing.",
    traveler: "You",
    prop: "Twin Watches",
    clockMode: "warning",
    visualMode: "blue",
    fragmentType: "watch",
    mainText: [
      "You return to your own body with Eli’s memories still burning inside you.",
      "For the first time, both of you remember pieces of the same truth.",
      "Every rescue from you triggered another sacrifice from Eli.",
      "Every sacrifice from Eli triggered another rescue from you.",
      "You were not fighting time. You were fighting each other’s grief."
    ],
    choiceText: "Join The Memories",
    quote: "Two people can love each other so much they become each other’s cage.",
    endingHint: "Only one traveler may leave with memory intact.",
  },

  {
    id: 42,
    title: "The Room Between Seconds",
    subtitle: "One second becomes a lifetime.",
    traveler: "You",
    prop: "White Room",
    clockMode: "frozen",
    visualMode: "white",
    fragmentType: "door",
    mainText: [
      "At exactly 11:11 PM, the second freezes.",
      "You and Eli step into a white room between moments.",
      "Outside, the world is paused.",
      "Inside, one second stretches long enough to say everything you avoided.",
      "Eli looks at you and says, \"I remember more than I told you.\""
    ],
    choiceText: "Listen To Eli",
    quote: "Some goodbyes need more than time can give.",
    endingHint: "Eli admits they remembered every timeline.",
  },

  {
    id: 43,
    title: "All the Ways You Saved Me",
    subtitle: "Eli sees the love hidden inside your failures.",
    traveler: "You",
    prop: "Rescue Archive",
    clockMode: "normal",
    visualMode: "blue",
    fragmentType: "museum",
    mainText: [
      "The room fills with every timeline where you tried to save Eli.",
      "You running through rain.",
      "You breaking doors.",
      "You screaming into phones.",
      "You choosing one more loop even after losing another piece of yourself."
    ],
    choiceText: "Let Eli Watch",
    quote: "You loved me so hard it almost destroyed you.",
    endingHint: "Eli reaches for your hand, but their fingers flicker.",
  },

  {
    id: 44,
    title: "All the Ways I Saved You",
    subtitle: "Eli’s sacrifices outnumber your memories.",
    traveler: "You",
    prop: "Eli Archive",
    clockMode: "warning",
    visualMode: "orange",
    fragmentType: "museum",
    mainText: [
      "Now Eli’s timelines appear.",
      "There are more than yours.",
      "Dozens. Hundreds.",
      "Eli pulling you from fires, trains, hospitals, bridges, streets, and rooms you never knew existed.",
      "The archive counter stops at 300, then breaks."
    ],
    choiceText: "Watch Eli’s Archive",
    quote: "You thought Eli was waiting to be saved. Eli was the first rescuer.",
    endingHint: "The museum cannot count Eli’s remaining sacrifices.",
  },

  {
    id: 45,
    title: "The Timeline That Wants One of You",
    subtitle: "The enemy is not evil. It is balance.",
    traveler: "You",
    prop: "Timeline Core",
    clockMode: "collapse",
    visualMode: "red",
    fragmentType: "door",
    mainText: [
      "The timeline core appears.",
      "It is not a monster. It does not hate you.",
      "It is a rule.",
      "Two travelers cannot keep the same ending.",
      "One may live with memory. One must become the goodbye."
    ],
    choiceText: "Face The Core",
    quote: "A rule does not need cruelty to break your heart.",
    endingHint: "The core asks: Save the one you love, or become the one they lose.",
  },

  {
    id: 46,
    title: "The Choice That Isn’t a Choice",
    subtitle: "You try to sacrifice yourself, but Eli already did.",
    traveler: "You",
    prop: "Final Command",
    clockMode: "warning",
    visualMode: "red",
    fragmentType: "message",
    mainText: [
      "You choose to die so Eli can live.",
      "For a second, the timeline accepts.",
      "Then the command is rejected.",
      "A message from Eli appears before your choice can complete.",
      "\"Do not let them die for me again.\""
    ],
    choiceText: "Override The Command",
    quote: "You cannot sacrifice yourself for someone who already sacrificed first.",
    endingHint: "Eli locked your death out of the final timeline.",
  },

  {
    id: 47,
    title: "Eli Remembers Everything",
    subtitle: "Eli was never forgetting. Eli was protecting you.",
    traveler: "You",
    prop: "Full Memory",
    clockMode: "frozen",
    visualMode: "orange",
    fragmentType: "memory",
    mainText: [
      "You finally understand.",
      "Eli did not slowly remember the loops.",
      "Eli remembered all of them from the beginning.",
      "Every time you looked at Eli like it was the first time, Eli had already lost you hundreds of times.",
      "They pretended not to know because they thought the truth would destroy you."
    ],
    choiceText: "Hold Eli",
    quote: "Every time you looked at me like it was the first time, I had already lost you hundreds of times.",
    endingHint: "Eli’s body begins to fade from the white room.",
  },

  {
    id: 48,
    title: "The Final Rescue",
    subtitle: "Eli moves first one last time.",
    traveler: "You",
    prop: "Final Watch",
    clockMode: "collapse",
    visualMode: "red",
    fragmentType: "watch",
    mainText: [
      "You prepare one final rescue.",
      "A loophole. A reversal. A way to force the timeline to take you instead.",
      "But Eli smiles through tears.",
      "They were earlier again.",
      "Eli transfers every remaining timeline permission into your broken watch."
    ],
    choiceText: "Stop Eli",
    quote: "The final rescue was never yours to perform.",
    endingHint: "Eli begins disappearing from every timeline at once.",
  },

  {
    id: 49,
    title: "You Were Never the Only One Trying",
    subtitle: "The last door was Eli’s gift.",
    traveler: "You",
    prop: "The Last Door",
    clockMode: "frozen",
    visualMode: "white",
    fragmentType: "door",
    mainText: [
      "Eli tells you the truth of the final door.",
      "Timeline 050 was not created by you.",
      "It was created by Eli using every memory they had left.",
      "Not as a world where Eli survives.",
      "As a world where you finally can."
    ],
    choiceText: "Enter The Last Timeline",
    quote: "You were never the only one trying.",
    endingHint: "The Last Door opens into morning light.",
  },

  {
    id: 50,
    title: "The Last Timeline",
    subtitle: "There is no rescue left. Only goodbye.",
    traveler: "You",
    prop: "Two Coffees",
    clockMode: "frozen",
    visualMode: "white",
    fragmentType: "final",
    specialMode: "finalChoice",
    mainText: [
      "You enter the last timeline.",
      "There is no accident.",
      "No countdown.",
      "No siren.",
      "Only a quiet room, morning light, and two cups of coffee on the table.",
      "Eli is sitting there, smiling like nothing ever broke.",
      "For one impossible moment, you think you saved them.",
      "Then Eli says:",
      "\"This is not the world where I survive.\"",
      "\"This is the world where you finally do.\""
    ],
    choiceText: "Choose",
    quote: "In every timeline, I chose the one where you lived.",
    endingHint: "Hold On, or Let Go.",
    finalChoices: {
      holdOn: {
        maxBeforeCollapse: 3,
        buttonText: "Hold On",
        lines: [
          "Love cannot become a cage.",
          "The room begins to break. Eli’s voice becomes harder to remember.",
          "Your obsession is tearing the world apart. Is this what love looks like to you?",
          "11:11 PM shakes violently. The letters blur. The world cannot survive your refusal."
        ],
      },
      letGo: {
        buttonText: "Let Go",
        successTitle: "Final Goodbye",
        quote: "In every timeline, I chose the one where you lived.",
        lines: [
          "You let go.",
          "The broken watch stops screaming.",
          "The room fills with warm white light.",
          "Eli smiles, not because leaving is easy, but because you finally understand.",
          "\"I didn’t leave because you failed to save me.\"",
          "\"I left because I finally saved you.\"",
          "\"Now live the life I kept giving back to you.\""
        ],
        finalLine: "Now live the life I kept giving back to you.",
      },
    },
  },
];

const timelineClockModes = {
  normal: {
    label: "Normal",
    description: "The 11:11 PM clock flickers faintly.",
  },
  warning: {
    label: "Warning",
    description: "The 11:11 PM clock shakes, brightens, or begins counting down.",
  },
  frozen: {
    label: "Frozen",
    description: "The clock freezes at 11:11 PM. Time refuses to move.",
  },
  collapse: {
    label: "Collapse",
    description: "The clock glitches, tears, and corrupts the screen.",
  },
};

const timelineVisualModes = {
  blue: {
    label: "Cold Blue",
    description: "Main player perspective. Grief, mystery, time pressure.",
  },
  red: {
    label: "Red Station",
    description: "Timeline danger, rule exposure, universe-level mystery.",
  },
  orange: {
    label: "Warm Orange",
    description: "Eli perspective, sacrifice, memory warmth.",
  },
  white: {
    label: "Warm White",
    description: "Final timeline, acceptance, letting go.",
  },
  reversed: {
    label: "Reversed Eli Mode",
    description: "EP.39 perspective flip. Player becomes Eli.",
  },
};

const timelineArchiveFragments = timelineEpisodes.map((episode) => ({
  id: episode.id,
  title: episode.title,
  fragmentType: episode.fragmentType,
  prop: episode.prop,
  traveler: episode.traveler,
  quote: episode.quote,
}));

const timelineFinalLogic = {
  finalEpisodeId: 50,
  holdOnStorageKey: "timeline_hold_on_count",
  archiveStorageKey: "timeline_archive_fragments",
  completedStorageKey: "timeline_completed",
  letGoUnlocksFinalMemory: true,
  finalMemoryCard: {
    title: "Save This Timeline",
    quote: "In every timeline, I chose the one where you lived.",
    subtitle: "The Last Timeline · Final Memory",
    shareText:
      "I didn’t leave because you failed to save me. I left because I finally saved you.",
  },
};

function getTimelineEpisode(id) {
  return timelineEpisodes.find((episode) => episode.id === Number(id)) || null;
}

function getNextTimelineEpisode(id) {
  const nextId = Number(id) + 1;
  return getTimelineEpisode(nextId);
}

function getTimelineProgress(id) {
  const current = Math.min(Math.max(Number(id) || 1, 1), timelineEpisodes.length);
  return {
    current,
    total: timelineEpisodes.length,
    percent: Math.round((current / timelineEpisodes.length) * 100),
  };
}

function isEliPerspectiveEpisode(id) {
  const episode = getTimelineEpisode(id);
  return episode
    ? episode.traveler === "Eli" || episode.specialMode === "eliPerspective"
    : false;
}

function isFinalTimelineEpisode(id) {
  const episode = getTimelineEpisode(id);
  return episode ? episode.specialMode === "finalChoice" : false;
}

window.timelineMeta = timelineMeta;
window.timelineEpisodes = timelineEpisodes;
window.timelineClockModes = timelineClockModes;
window.timelineVisualModes = timelineVisualModes;
window.timelineArchiveFragments = timelineArchiveFragments;
window.timelineFinalLogic = timelineFinalLogic;

window.getTimelineEpisode = getTimelineEpisode;
window.getNextTimelineEpisode = getNextTimelineEpisode;
window.getTimelineProgress = getTimelineProgress;
window.isEliPerspectiveEpisode = isEliPerspectiveEpisode;
window.isFinalTimelineEpisode = isFinalTimelineEpisode;

window.TIMELINE_META = timelineMeta;
window.TIMELINE_EPISODES = timelineEpisodes;
window.TIMELINE_CLOCK_MODES = timelineClockModes;
window.TIMELINE_VISUAL_MODES = timelineVisualModes;
window.TIMELINE_ARCHIVE_FRAGMENTS = timelineArchiveFragments;
window.TIMELINE_FINAL_LOGIC = timelineFinalLogic;
