/* =========================================================
   ZenAI Mystery Universe
   Series 02: The Last Timeline
   File: timeline-games.js
   Version: Playable Story Data v1.6

   重点：
   1. 保留 The Last Timeline 50集完整结构
   2. 前40集保留主线、状态字段、红眼联动、Eli视角反转
   3. EP.41 - EP.50 终章催泪强化
   4. Hold On 会让世界崩坏
   5. Let Go 才是 Eli 用所有时间线换来的最终礼物
========================================================= */

const timelineMeta = {
  universe: "ZenAI Mystery Universe",
  seriesId: "series-02",
  cnTitle: "最后的时间线",
  enTitle: "The Last Timeline",
  version: "v1.6",
  theme: "Time Travel / Sacrifice / Love / Letting Go",
  coreTime: "11:11 PM",
  coreProp: "Broken Watch",
  logline:
    "You spent 49 timelines trying to save Eli. In the 50th, you discover Eli was saving you too.",
  finalQuote:
    "In every timeline, I chose the one where you lived. Not because I wanted to leave. Because loving you meant giving you a future I could not stay in.",
};

function E(
  id,
  title,
  subtitle,
  traveler,
  prop,
  clockMode,
  visualMode,
  fragmentType,
  mainText,
  choiceText,
  quote,
  endingHint,
  extra = {}
) {
  return {
    id,
    title,
    subtitle,
    traveler,
    prop,
    clockMode,
    visualMode,
    fragmentType,
    mainText,
    choiceText,
    quote,
    endingHint,
    ...extra,
  };
}

const timelineEpisodes = [
  E(
    1,
    "The Night You Lost Them",
    "The first time 11:11 PM took Eli away.",
    "You",
    "Broken Watch",
    "normal",
    "blue",
    "message",
    [
      "At 11:08 PM, Eli sends a message that feels wrong before you even finish reading it.",
      "\"Don’t come looking for me.\"",
      "There is no explanation. No emoji. No second message. Just five words sitting on your screen like a door closing from the other side.",
      "You call once. No answer. Twice. No answer. By the third call, your hands are already shaking.",
      "The city outside is soaked in rain. Streetlights smear across the pavement.",
      "At 11:11 PM, you reach the crosswalk.",
      "White light swallows everything.",
      "When your vision returns, Eli is gone. No body. No ambulance. No witnesses. Only a broken watch beside a spilled cup of coffee.",
      "The watch hands are frozen at 11:11 PM.",
      "Then the entire world goes silent.",
    ],
    "Wake Up",
    "Some nights do not end. They reset.",
    "You open your eyes at 7:00 AM. Your phone buzzes. Eli is alive."
  ),

  E(
    2,
    "The Message That Shouldn’t Exist",
    "A warning appears before you ever write it.",
    "You",
    "Unsent Message",
    "normal",
    "blue",
    "message",
    [
      "You wake up gasping, still feeling rain on your skin.",
      "Eli: \"Coffee later?\"",
      "For three seconds, your heart believes mercy exists.",
      "Then you notice another message sitting in your draft box.",
      "\"You have tried this before.\"",
      "\"Do not trust 11:11 PM.\"",
      "You call Eli immediately. They answer with a sleepy laugh, annoyed and alive.",
      "You ask them not to go near the east crosswalk tonight.",
      "Eli pauses.",
      "\"How did you know I was going there?\"",
    ],
    "Call Eli",
    "The future left a warning in your own hands.",
    "Eli says a sentence you heard after their death, before they ever had a chance to say it."
  ),

  E(
    3,
    "One More Morning",
    "You try to stop the day before it begins.",
    "You",
    "Broken Watch",
    "normal",
    "blue",
    "watch",
    [
      "This time, you do not wait for fate to start moving.",
      "You arrive at Eli’s door before breakfast. You knock too hard. You say too much.",
      "Eli opens the door in an old sweater, holding a mug of coffee, alive in a way that hurts more than the memory of losing them.",
      "You beg them to stay home.",
      "They stay.",
      "For the first time, the day changes.",
      "At 11:10 PM, Eli squeezes your hand.",
      "\"See? We made it.\"",
      "At 11:11 PM, the ceiling light flickers.",
      "The broken watch in your pocket starts ticking backward.",
      "The accident has followed you inside.",
    ],
    "Hold Eli Back",
    "Fate does not need a street to find someone.",
    "The room bends around Eli. You reach for them, and the morning restarts."
  ),

  E(
    4,
    "The Broken Watch",
    "The watch remembers what you cannot.",
    "You",
    "Broken Watch",
    "normal",
    "blue",
    "watch",
    [
      "On the fourth morning, you stop screaming.",
      "You empty your pockets with the calm of someone who has run out of disbelief.",
      "Keys. Phone. Receipt. A small piece of glass.",
      "And the broken watch.",
      "It should have been left in the rain. It should not be here, warm from your pocket.",
      "The hands are still frozen at 11:11 PM.",
      "You turn it over and find engraving beneath scratches and old blood.",
      "\"For the one who must live.\"",
      "Inside is a tiny photograph of Eli, older and exhausted.",
      "Behind the photograph is a folded strip of paper.",
      "\"When the watch breaks completely, one of us stays gone.\"",
    ],
    "Open The Watch",
    "A gift from a future that has not forgiven you yet.",
    "For the first time, the watch ticks once without moving its hands."
  ),

  E(
    5,
    "The Street With No Cars",
    "You remove the accident. The ending remains.",
    "You",
    "City Map",
    "normal",
    "blue",
    "photo",
    [
      "You decide the universe is not magic. It is a system. A system can be broken.",
      "You block the east crosswalk. You clear every route. You make sure no cars can pass within three blocks.",
      "By 10:55 PM, the street is empty.",
      "By 11:05 PM, Eli is safe beside you.",
      "By 11:10 PM, the rain stops.",
      "The silence feels like victory.",
      "Then every traffic light turns red at once.",
      "At 11:11 PM, Eli looks at you and says, very softly, \"I think I have been here before.\"",
      "Nothing hits them.",
      "No car. No white light. No scream.",
      "Eli simply disappears.",
      "\"TIMELINE CORRECTION FAILED.\"",
    ],
    "Search The Street",
    "The accident was never the cause. It was only the shape grief chose first.",
    "A security camera captures the empty street. In the reflection, someone behind you is holding another watch."
  ),

  E(
    6,
    "The Train They Never Took",
    "The first time the clock fights back.",
    "You",
    "Train Ticket",
    "warning",
    "blue",
    "ticket",
    [
      "You stop trying to control the street. You choose distance instead.",
      "A train leaves the city at 9:40 PM.",
      "It does not pass the crosswalk. It does not pass the apartment. It does not pass any place where Eli has died.",
      "Eli follows you onto the train because they are beginning to understand one terrifying thing:",
      "You are not afraid of something that might happen.",
      "You are afraid of something that already has.",
      "At 11:08 PM, the carriage lights turn cold blue.",
      "At 11:09 PM, every passenger stops moving.",
      "At 11:11 PM, the speakers crackle.",
      "\"Timeline 006 will terminate at 11:11 PM.\"",
      "Every passenger turns toward Eli.",
      "\"Return what was borrowed.\"",
    ],
    "Run Through The Train",
    "Changing direction is not the same as escaping fate.",
    "Eli looks at the frozen passengers and whispers, \"Why does this feel familiar?\""
  ),

  E(
    7,
    "A Door Opens Twice",
    "Another version of you knows the rule.",
    "You",
    "Old Door",
    "normal",
    "blue",
    "door",
    [
      "The door appears on the seventh morning.",
      "It stands at the end of your hallway where there has only ever been a blank wall.",
      "You open it.",
      "The room beyond is not a room. It is the same hallway, but darker, older, soaked in dust.",
      "Another version of you sits on the floor holding Eli’s coat.",
      "\"You are early,\" they say.",
      "You ask where Eli is.",
      "The other you laughs once, but it breaks before it becomes sound.",
      "\"Which Eli?\"",
      "On the wall are hundreds of tally marks.",
      "\"Do not let Eli know how much they remember.\"",
      "\"They are not the one who started this. We are only catching up.\"",
    ],
    "Step Inside",
    "Some doors do not open into rooms. They open into grief that learned to wait.",
    "Before you can ask what Eli remembers, the other you is pulled backward into darkness."
  ),

  E(
    8,
    "The First Paradox",
    "You tell Eli too much, too early.",
    "You",
    "Unsent Message",
    "warning",
    "blue",
    "message",
    [
      "You are tired of lying to someone you keep losing.",
      "So you tell Eli everything.",
      "The first message. The crosswalk. The watch. The apartment. The train. The door.",
      "You expect Eli to think you are losing your mind.",
      "They do not.",
      "\"What time?\" Eli asks.",
      "\"11:11 PM.\"",
      "Eli closes their eyes.",
      "For a moment, their face changes.",
      "\"How many times have you watched me die?\" they ask.",
      "Your phone lights up with a new unsent draft.",
      "\"Do not answer that.\"",
      "The clock on the wall jumps from 4:16 PM to 11:11 PM.",
      "\"Wait,\" Eli says. \"I know this part.\"",
    ],
    "Answer Eli",
    "Truth can be a wound if it arrives before memory is ready.",
    "The timeline forces a reset the moment Eli almost remembers too much."
  ),

  E(
    9,
    "The Room Full of Tomorrow",
    "The future has been collecting your failures.",
    "You",
    "Wall of Photos",
    "normal",
    "blue",
    "photo",
    [
      "The impossible room returns.",
      "The broken watch leads you there.",
      "Behind the old door is a room covered in photographs.",
      "Not memories. Evidence.",
      "Each photo is labeled with a timeline number.",
      "Timeline 001.",
      "Timeline 006.",
      "Timeline 012.",
      "Some photos show endings you remember. Some show failures you have not reached.",
      "On one wall, there are pictures of you.",
      "In some, you are alive.",
      "In others, Eli is holding your body.",
      "The final row has only two frames.",
      "Timeline 049 is filled with a photograph of Eli standing before a white door.",
      "Timeline 050 is empty.",
      "\"This one is not yours.\"",
    ],
    "Touch The Last Photo",
    "Tomorrow is not coming. It is waiting to see who pays for it.",
    "Behind the empty Timeline 050 frame, you hear Eli crying from the other side of the wall."
  ),

  E(
    10,
    "Stop Saving Me",
    "Eli’s voice comes from a future you have not reached.",
    "You",
    "Broken Watch",
    "frozen",
    "blue",
    "audio",
    [
      "On the tenth morning, the watch will not open.",
      "At 11:11 AM, exactly twelve hours before the usual ending, the watch opens by itself.",
      "There is no photograph inside now.",
      "Only a small speaker hidden behind the cracked face.",
      "Static breathes through it.",
      "Then Eli’s voice begins.",
      "\"If you hear this, it means you started again.\"",
      "\"I know you think love means trying one more time.\"",
      "\"But every time you save me, something else takes your place.\"",
      "\"Every time you refuse to let me go, another part of you disappears.\"",
      "\"Please.\"",
      "\"Stop saving me.\"",
      "\"You were never supposed to be the one chasing me.\"",
    ],
    "Replay The Voice",
    "The person you are trying to save is begging you to stop, and you still do not know why.",
    "The recording ends with a second voice in the background. It is yours, dying in Eli’s arms."
  ),

  E(
    11,
    "The Timeline Tax",
    "Every rescue takes something from you.",
    "You",
    "Memory Fragment",
    "normal",
    "blue",
    "memory",
    [
      "You do not notice the first thing you lose.",
      "That is what makes it cruel.",
      "On the eleventh morning, Eli asks what song you want to play while making coffee.",
      "There has always been one song. The song Eli plays when they are happy.",
      "But when you open your mouth, the title is gone.",
      "Not forgotten like a word on the tip of your tongue.",
      "Gone like it was never written inside you.",
      "\"You forgot it,\" Eli says softly.",
      "The watch grows warm in your palm.",
      "\"EVERY RESCUE COSTS A MEMORY.\"",
      "You can still remember exactly how Eli dies.",
      "You just cannot remember how they sounded when they were alive.",
    ],
    "Keep Going",
    "You are saving a life by losing the reasons you loved it.",
    "A photo of Eli laughing remains on your phone, but the audio attached to it is silent."
  ),

  E(
    12,
    "The Hospital Without Names",
    "Even safety cannot hold someone who does not belong.",
    "You",
    "Hospital Bracelet",
    "warning",
    "blue",
    "photo",
    [
      "You choose the most reasonable place left.",
      "A hospital has lights that never sleep. Cameras in the halls. Doors that lock.",
      "You bring Eli there before sunset.",
      "A nurse wraps a bracelet around Eli’s wrist.",
      "The bracelet prints blank.",
      "At 10:58 PM, every patient chart in the hospital loses its name.",
      "At 11:08 PM, the lights above Eli’s bed begin blinking like a countdown.",
      "The doctor returns with an expression too empty to be human.",
      "\"This patient does not belong to this timeline.\"",
      "At 11:11 PM, the heart monitor screams once.",
      "Then becomes a flat line.",
      "But Eli is still sitting up.",
      "The line on the monitor is not Eli’s.",
      "It is yours.",
    ],
    "Grab Eli’s Hand",
    "A safe room means nothing if time itself wants someone gone.",
    "Eli’s hospital bracelet finally prints a name. It prints yours."
  ),

  E(
    13,
    "The Photo That Fades First",
    "The world begins erasing proof that Eli existed.",
    "You",
    "Fading Photo",
    "normal",
    "blue",
    "photo",
    [
      "You start collecting proof.",
      "Photos. Screenshots. Receipts. Voice memos.",
      "You print your favorite photo of Eli and tape it above your desk.",
      "At first, only the color fades.",
      "Then the café sign disappears.",
      "Then Eli’s face begins to vanish from the paper.",
      "You press your palm against the photo like you can hold the ink in place.",
      "\"Stay,\" you whisper.",
      "By 11:11 PM, Eli is gone from the photo.",
      "Only you remain, smiling at an empty space.",
      "\"ONE OF YOU HAS ALREADY BEEN ERASED.\"",
    ],
    "Save The Photo",
    "Some memories do not fade. They are taken.",
    "The café in the photo no longer exists on the map, but its address now points to the red station."
  ),

  E(
    14,
    "Seven Minutes Earlier",
    "The watch gives you less time than before.",
    "You",
    "Broken Watch",
    "warning",
    "blue",
    "watch",
    [
      "This reset is wrong from the first breath.",
      "You do not wake up at 7:00 AM.",
      "You wake up running.",
      "11:04 PM.",
      "Seven minutes.",
      "The city around you is already bent toward the ending.",
      "Street signs point in impossible directions.",
      "At 11:08 PM, Eli finally calls.",
      "\"Do not come closer,\" they say.",
      "\"I think this is the one where you die.\"",
      "At 11:10 PM, you see Eli across the street.",
      "They are crying.",
      "At 11:11 PM, Eli pushes you away from nothing you can see.",
      "Something invisible takes their place.",
    ],
    "Try Another Route",
    "Sometimes the universe gives you time only to prove it is not enough.",
    "As the reset begins, you hear Eli say, \"I knew where it would come from.\""
  ),

  E(
    15,
    "The Stranger at the Crosswalk",
    "Someone saves you before Eli can die.",
    "You",
    "Watch Shard",
    "normal",
    "blue",
    "watch",
    [
      "You return to the crosswalk because grief keeps circling its first wound.",
      "This time, you do not bring Eli.",
      "At 11:10 PM, your phone displays an incoming call from Eli.",
      "You do not answer.",
      "Then headlights appear from a street that has been blocked for construction all week.",
      "The car is not coming for Eli.",
      "It is coming for you.",
      "A stranger grabs your wrist and pulls you backward.",
      "Same height as Eli.",
      "Same coat.",
      "Same way of touching your wrist like they are afraid you might vanish.",
      "For half a second, they turn.",
      "You see the watch in their hand.",
      "It is more broken than yours.",
      "A shard falls to the pavement.",
    ],
    "Chase The Stranger",
    "The person you are saving may have saved you first.",
    "The watch shard is engraved with Eli’s initial."
  ),

  E(
    16,
    "The Notebook of Failed Worlds",
    "Another traveler has been keeping records.",
    "You",
    "Failed Worlds Notebook",
    "normal",
    "blue",
    "letter",
    [
      "The watch shard leads you to a storage locker you have never rented.",
      "Inside: a box, a train ticket, three dead phones, and a black notebook wrapped in plastic.",
      "Some pages are yours.",
      "Timeline 003: Keep Eli home. Failed.",
      "Timeline 006: Leave by train. Failed.",
      "Timeline 014: Seven-minute reset. Failed.",
      "Then the handwriting changes.",
      "Timeline 021: They almost saw me at the crosswalk.",
      "Timeline 044: They died before I reached the hospital.",
      "Timeline 087: I saved them, but they forgot my name.",
      "\"They keep trying to save me.\"",
      "\"They don’t know I started first.\"",
      "At the bottom of the page is one letter.",
      "E.",
    ],
    "Read More",
    "You were never the only one fighting time.",
    "The next page contains a list titled: Ways to keep them alive without letting them know."
  ),

  E(
    17,
    "The Song From Another Life",
    "A song that only exists inside broken timelines.",
    "You",
    "Unknown Song",
    "normal",
    "blue",
    "audio",
    [
      "The missing song returns before you remember its name.",
      "Eli hums it while washing a cup.",
      "A soft melody. Three rising notes. A pause.",
      "\"Where did you learn that?\" you ask.",
      "\"I don’t know.\"",
      "You record them humming it.",
      "The file saves successfully.",
      "That night, Eli sings under their breath while pretending to sleep.",
      "\"If I disappear, remember the life I gave back to you.\"",
      "At 7:00 AM, the recording file changes its name.",
      "goodbye_107.mp3.",
      "The number makes Eli cry when they see it.",
    ],
    "Record The Song",
    "Some songs are not written. They survive.",
    "When you play the audio backward, Eli’s voice says, \"I have watched you die before.\""
  ),

  E(
    18,
    "The World Where You Never Met",
    "You try to erase the beginning.",
    "You",
    "First Meeting Place",
    "normal",
    "blue",
    "memory",
    [
      "You decide love is the first mistake.",
      "Not because you regret Eli.",
      "Because you cannot bear the thought that being loved by you is what put them in the path of time.",
      "So you go back further.",
      "Before the message.",
      "Before the watch.",
      "Before the coffee.",
      "The day you met, you do not enter the café.",
      "At 11:11 PM, you stand alone under a streetlight and wait for nothing to happen.",
      "Then someone runs toward you.",
      "Eli.",
      "\"I don’t know you,\" they say.",
      "Behind them, a car loses control.",
      "Eli pushes you out of the way before you can move.",
      "Even in a world where you never met, Eli finds a way to save you first.",
    ],
    "Step Toward Eli",
    "Love does not always begin with memory.",
    "As the world resets, stranger-Eli whispers, \"I think I came here for you.\""
  ),

  E(
    19,
    "The Empty Seat Beside You",
    "The world remembers a date you lost.",
    "You",
    "Movie Ticket",
    "normal",
    "blue",
    "ticket",
    [
      "You wake in a movie theater.",
      "The seat beside you is empty.",
      "But the popcorn there is still warm.",
      "Two tickets are in your hand.",
      "One has your name.",
      "The other has Eli’s name, fading one letter at a time.",
      "The screen brightens.",
      "A memory begins playing.",
      "You and Eli sitting in this same theater, years ago, whispering jokes through a terrible film.",
      "The Eli on the screen turns away from memory and looks directly at you.",
      "\"You keep saving my ending,\" they say from the screen.",
      "\"But you are losing all the middle parts.\"",
    ],
    "Watch The Screen",
    "An empty seat can be louder than a scream.",
    "The film ends with Eli sitting alone, watching your seat disappear."
  ),

  E(
    20,
    "The First Time You Gave Up",
    "You stop running. The world punishes the memory.",
    "You",
    "Silent Watch",
    "collapse",
    "blue",
    "memory",
    [
      "You are exhausted in a way sleep cannot repair.",
      "For the first time, you decide not to move.",
      "No phone calls.",
      "No train tickets.",
      "No hospital.",
      "You place the broken watch on the table and sit across from Eli.",
      "\"I’m tired,\" you admit.",
      "\"Then rest,\" Eli says.",
      "At 11:11 PM, nothing happens.",
      "For one beautiful second, you think surrender has saved you both.",
      "Then Eli’s name disappears from your phone.",
      "The messages vanish.",
      "The photos empty themselves.",
      "The world does not take Eli’s body this time.",
      "It takes the fact that Eli ever existed.",
      "\"TIMELINE 020: MEMORY COLLAPSE.\"",
    ],
    "Remember Eli",
    "Giving up is not the same as letting go.",
    "Only one thing still remembers Eli: the second watch shard hidden under your skin."
  ),

  E(
    21,
    "A Handwriting You Know",
    "Eli has written from beyond your failures.",
    "You",
    "Failed Worlds Notebook",
    "normal",
    "blue",
    "letter",
    [
      "The notebook does not leave with the reset.",
      "That is the first miracle of Timeline 021.",
      "It sits on your desk in the morning, damp from rain that has not fallen yet.",
      "You compare the handwriting to an old birthday card Eli gave you years ago.",
      "Same tilted letters.",
      "Same pressure on the last stroke of your name.",
      "The page is dated after the night Eli died.",
      "Some entries were written in places you have not reached yet.",
      "A hospital without names.",
      "A red station.",
      "A white room between seconds.",
      "One sentence stops everything inside you.",
      "\"If they find this, I failed to protect them again.\"",
      "Again.",
      "\"They still think I am the one being saved.\"",
    ],
    "Trace The Ink",
    "The handwriting of the dead can still arrive early.",
    "A new page appears with only three words: Original Timeline First."
  ),

  E(
    22,
    "The Version of You That Died",
    "The original ending was never Eli’s death.",
    "You",
    "Original Timeline",
    "frozen",
    "red",
    "memory",
    [
      "The words Original Timeline First burn through the notebook page.",
      "You fall into rain.",
      "Same street.",
      "Same white light.",
      "But this time, the scene is wrong.",
      "Eli is not in danger.",
      "You are.",
      "A version of yourself steps into the road, distracted by a message you never get to read.",
      "A car appears from nowhere.",
      "Eli sees it first.",
      "They could stay on the sidewalk.",
      "Instead, Eli runs.",
      "They push you away with both hands.",
      "The white light hits you anyway.",
      "The body on the pavement is yours.",
      "Eli picks up the watch.",
      "The hands move backward for the first time.",
      "\"No. Not this ending.\"",
    ],
    "Watch The Original",
    "Before you tried to save Eli, Eli broke time to save you.",
    "The original body on the pavement was yours, and Eli was the first person to reset the world."
  ),

  E(
    23,
    "The Message Under the Floor",
    "Eli hid the truth where only grief would search.",
    "You",
    "Hidden Recorder",
    "normal",
    "blue",
    "audio",
    [
      "Under the bed, beneath a loose floorboard, there is a small recorder wrapped in Eli’s scarf.",
      "You press play.",
      "Static opens first.",
      "Then Eli’s voice.",
      "\"I found a way to move through time too.\"",
      "\"I only wanted to save you once.\"",
      "\"But time does not give gifts. It makes trades.\"",
      "\"The first time I saved you, it asked for my future.\"",
      "\"The second time, it asked for your memory of my laugh.\"",
      "\"The third time, it asked whether I was willing to become the one you would keep losing.\"",
      "In the background of the audio, you hear yourself crying.",
      "Eli whispers:",
      "\"Please live long enough to hate me for this.\"",
    ],
    "Play The Recorder",
    "A secret can survive beneath the floor longer than a body can survive time.",
    "The recorder contains one final file labeled: DO NOT PLAY BEFORE TIMELINE 039."
  ),

  E(
    24,
    "The Timeline Where Eli Lied",
    "Eli’s dreams are not dreams.",
    "You",
    "Dream Journal",
    "normal",
    "blue",
    "letter",
    [
      "Eli has been lying badly.",
      "You notice it in the way they stop talking when clocks appear in movies.",
      "You find the dream journal in their bag by accident.",
      "The cover says Dreams, but the pages read like reports from places you have not survived yet.",
      "A hospital where every name disappears.",
      "A red station where no trains arrive.",
      "A white room where one second lasts long enough to say goodbye.",
      "A line appears again and again:",
      "\"Do not let them know I remember.\"",
      "When Eli finds you reading, they do not get angry.",
      "They look relieved.",
      "\"In a timeline where telling you did not get you killed,\" Eli says.",
      "\"Traveler Eli memory leak detected.\"",
    ],
    "Ask Eli Again",
    "A lie told to protect you still cuts like truth.",
    "A thin crack of blue light appears on Eli’s wrist, shaped like the hands of a watch."
  ),

  E(
    25,
    "The Red Station",
    "A station between endings.",
    "You",
    "Red Station Ticket",
    "frozen",
    "red",
    "ticket",
    [
      "At 11:11 PM, the apartment door opens into a train station.",
      "Everything is red.",
      "Red tiles. Red lights. Red fog moving along the floor like something breathing.",
      "Thousands of clocks hang from the ceiling, all frozen at 11:11 PM.",
      "Eli goes pale.",
      "\"I know this place,\" they whisper.",
      "A ticket appears in your hand.",
      "Passenger: You. Destination: Original Debt.",
      "A second ticket appears in Eli’s hand.",
      "Passenger: Eli. Destination: Substitute Ending.",
      "There are no trains on the tracks.",
      "Only doors.",
      "\"Two travelers cannot leave the same timeline together.\"",
      "Eli grips your sleeve.",
      "\"Do not choose a door yet. That is how it separates us.\"",
    ],
    "Enter The Platform",
    "Some stations are built for people who cannot arrive together.",
    "Behind a wall of broken clocks, a fourth rule waits under dried blood."
  ),

  E(
    26,
    "The Rules Written in Blood",
    "Time finally explains its cruelty.",
    "You",
    "Timeline Rules",
    "warning",
    "red",
    "museum",
    [
      "The red station does not have maps.",
      "It has rules.",
      "Rule One: \"One life may be returned.\"",
      "Rule Two: \"One memory must be paid.\"",
      "Rule Three: \"Two travelers cannot keep the same ending.\"",
      "A fourth rule has been covered in blood.",
      "Eli grabs your hand.",
      "\"Don’t.\"",
      "\"Why?\"",
      "\"Because I wiped it away once.\"",
      "Your fingers touch the blood anyway.",
      "The fourth rule appears beneath it.",
      "\"The one who remembers most must choose last.\"",
      "Eli closes their eyes.",
      "Eli remembers more.",
      "Eli has always remembered more.",
    ],
    "Wipe The Wall",
    "A rule written in blood has already been broken.",
    "The fourth rule reveals why Eli keeps arriving before you."
  ),

  E(
    27,
    "The Life You Borrowed",
    "Your survival has Eli’s fingerprints all over it.",
    "You",
    "Borrowed Life",
    "normal",
    "blue",
    "memory",
    [
      "The station opens into a room made of moving memories.",
      "At first, you think they are yours.",
      "Then you see Eli in every one.",
      "Eli missing a train so you could catch it.",
      "Eli stepping into smoke so you would wake up outside the fire.",
      "Eli closing a door from the wrong side.",
      "Eli pressing the watch while your body lies still on a hospital floor.",
      "You called it luck.",
      "But luck has Eli’s hands.",
      "Luck has Eli’s coat.",
      "Luck has Eli whispering, \"Don’t tell them. Let them live.\"",
      "Every version of your ordinary life is built on something Eli gave up quietly.",
    ],
    "Keep Watching",
    "You called it luck because Eli never let you see the cost.",
    "The final memory shows Eli carving your name into the back of their watch."
  ),

  E(
    28,
    "Do Not Follow Me",
    "Eli runs because your love is becoming another loop.",
    "You",
    "Eli’s Note",
    "warning",
    "blue",
    "letter",
    [
      "Eli disappears before sunset.",
      "No call.",
      "No final message.",
      "Just an empty chair, a cooling cup of coffee, and a note on the kitchen table.",
      "\"If you love me, don’t follow me this time.\"",
      "Of course you follow.",
      "Love has become a reflex stronger than reason.",
      "Every streetlight turns toward you like an eye.",
      "The closer you get to Eli, the more the world tears.",
      "At 11:09 PM, you find Eli at the red station entrance.",
      "They are holding both tickets.",
      "\"Every time you follow me, time learns how to hurt you better.\"",
      "You reach anyway.",
      "The moment your fingers touch, the timeline tears open.",
    ],
    "Follow Eli",
    "Sometimes chasing someone is how you lose them faster.",
    "Inside the tear, you see a house that remembers two versions of your grief."
  ),

  E(
    29,
    "The House That Remembers Both of You",
    "Two lives haunt the same home.",
    "You",
    "Memory House",
    "normal",
    "blue",
    "memory",
    [
      "The tear drops you into a house you have never seen but somehow know how to walk through.",
      "Two sets of keys hang by the door.",
      "Two coats on the rack.",
      "Two coffee cups in the sink.",
      "But every room tells two different stories.",
      "In one version of the bedroom, you slept alone after losing Eli.",
      "In another, Eli slept alone after losing you.",
      "The house is not haunted by ghosts.",
      "It is haunted by outcomes.",
      "\"They were not the only one grieving.\"",
      "\"They were not the only one waiting.\"",
      "Eli stands in the doorway behind you.",
      "\"I lived here too,\" they say.",
      "\"After you died.\"",
      "The floorboards open beneath the bed.",
    ],
    "Touch The Wall",
    "A home can remember every version of heartbreak.",
    "Beneath the house, Eli’s second watch waits in a box marked For the one who keeps forgetting."
  ),

  E(
    30,
    "The Second Watch",
    "Eli’s watch is older than yours.",
    "You",
    "Eli’s Watch",
    "frozen",
    "blue",
    "watch",
    [
      "The box under the floor is wrapped in a scarf you remember and do not remember.",
      "Inside is a second broken watch.",
      "Older than yours.",
      "More damaged.",
      "The glass is cracked in three directions. The strap is burned.",
      "On the back, carved by hand:",
      "\"In every timeline, I chose you.\"",
      "Your watch begins to tick.",
      "Eli’s watch answers.",
      "Two sounds.",
      "Two heartbeats.",
      "Two travelers.",
      "Your circle began with losing Eli.",
      "Eli’s circle began with losing you.",
      "When both watches touch, the air splits open.",
      "\"THE TIMELINE MUSEUM.\"",
    ],
    "Join The Watches",
    "The second watch proves the first sacrifice was never yours.",
    "When both watches touch, the Timeline Museum opens."
  ),

  E(
    31,
    "The Timeline Museum",
    "Every failed world has been preserved.",
    "You",
    "Timeline Museum",
    "frozen",
    "red",
    "museum",
    [
      "The Timeline Museum is not a building.",
      "It is a place grief built because neither of you would stop trying.",
      "Every hallway is lined with cases.",
      "Every case contains one failed world.",
      "Timeline 001: rainwater on pavement, one broken watch, your scream caught forever in white light.",
      "Timeline 006: a frozen train carriage, passengers turned toward Eli.",
      "Timeline 020: an empty chair across from you, a world that no longer knows Eli’s name.",
      "Timeline 030: two watches touching inside a house that remembered both of your griefs.",
      "In one corner, almost hidden, there is a small exhibit that does not belong to your story.",
      "A faded photograph.",
      "A red thread stitched through the torn edge.",
      "A dark eye reflected faintly in the glass.",
      "\"Some goodbyes happen in other rooms.\"",
      "For one second, you hear another voice, distant and warm:",
      "\"Don’t be afraid of the dark anymore.\"",
      "Then the museum lights flicker red.",
      "\"ORIGINAL TIMELINE EXHIBIT.\"",
    ],
    "Enter The Original Exhibit",
    "Every universe keeps its grief somewhere.",
    "The largest exhibit is labeled: Original Timeline — You Died.",
    {
      universeEasterEgg: {
        linkedSeries: "The Red Eye Files: Final Goodbye",
        object: "A faded photograph stitched with a red thread.",
        label: "Some goodbyes happen in other rooms.",
        meaning:
          "A quiet universe-level connection to The Red Eye Files, hinting that the Archive and Museum belong to the same emotional universe.",
      },
    }
  ),

  E(
    32,
    "The Birthday You Forgot",
    "You remember Eli’s death better than Eli’s life.",
    "You",
    "Birthday Candle",
    "normal",
    "blue",
    "memory",
    [
      "The museum forces you into a smaller room.",
      "Only a kitchen table, one birthday cake, and a single candle that never melts.",
      "You know the exact second Eli dies.",
      "You know the sound of the watch before every reset.",
      "You know the crosswalk, the hospital, the train, the station, the house.",
      "But when Eli asks, \"What day is my birthday?\" you cannot answer.",
      "The silence hurts more than the question.",
      "You search yourself for the date.",
      "You find only 11:11 PM.",
      "\"You remember how I die,\" Eli says.",
      "\"Do you still remember how I lived?\"",
      "Inside the candle flame, you see small ordinary days you failed to protect.",
      "Eli laughing with flour on their cheek.",
      "Eli saying your name in the morning like the world had not become impossible yet.",
    ],
    "Remember Eli’s Life",
    "Obsession remembers the wound. Love remembers the person.",
    "The candle melts into the shape of 11:11, and the museum opens the next exhibit."
  ),

  E(
    33,
    "The World Where Eli Stayed",
    "You finally save Eli, but the cost moves to you.",
    "You",
    "Borrowed Ending",
    "normal",
    "blue",
    "memory",
    [
      "The next exhibit is impossible because it looks like mercy.",
      "You wake in a quiet kitchen.",
      "Eli is alive.",
      "Just alive, barefoot on the kitchen floor, making coffee.",
      "For the first time in thirty-three timelines, 11:11 PM passes without taking Eli.",
      "The clock changes to 11:12.",
      "You laugh so hard it sounds like grief leaving your body.",
      "For one perfect minute, you believe you won.",
      "Then your hand passes through Eli’s sleeve.",
      "Your fingers are transparent.",
      "Eli stops smiling.",
      "\"This is why I kept leaving,\" they whisper.",
      "\"A saved life must be borrowed from someone else.\"",
    ],
    "Hide Your Hand",
    "A saved life can still be borrowed from someone else.",
    "Eli whispers: This is why I kept leaving."
  ),

  E(
    34,
    "A Perfect Day, Almost",
    "The day Eli wanted to give you.",
    "You",
    "Two Coffees",
    "normal",
    "orange",
    "photo",
    [
      "The museum gives you one day without rules.",
      "That is how you know it is dangerous.",
      "You and Eli wake in a city that has not learned to hurt you yet.",
      "No hiding.",
      "No running.",
      "No checking every intersection for death.",
      "Eli buys two coffees from the café that disappeared in Timeline 013.",
      "You walk through the city together.",
      "You sit in a park and Eli tells you a joke so bad you laugh before they finish it.",
      "At sunset, Eli takes a photo of you.",
      "Not for evidence.",
      "Just because they want to remember you smiling.",
      "\"This is the day I kept trying to give you.\"",
      "The sun stops moving.",
      "\"A perfect day was all I could steal.\"",
    ],
    "Stay In The Day",
    "A perfect day can hurt more than a terrible one.",
    "The sun stops moving, and the perfect day begins to crack around the edges."
  ),

  E(
    35,
    "The Cost of Staying",
    "The world cannot survive a stolen ending.",
    "You",
    "Frozen Sky",
    "collapse",
    "orange",
    "memory",
    [
      "At first, the cracks are beautiful.",
      "Thin gold lines across the sky.",
      "Then people lose their shadows.",
      "Then every window reflects a different version of Eli dying.",
      "The perfect day begins repeating itself in pieces.",
      "Coffee spills upward.",
      "The postcard rewrites its message.",
      "The park bench appears in the middle of the street.",
      "Every clock in the city becomes 11:11 PM.",
      "Not ticking.",
      "Accusing.",
      "\"BORROWED ENDING FAILURE.\"",
      "\"ONE TRAVELER MUST RELEASE THE OTHER.\"",
      "Eli steps toward the door.",
      "You pull them back.",
      "The city screams.",
    ],
    "Find The Core",
    "Keeping someone can become another way of destroying them.",
    "A white door appears inside the black one, leading to the timeline core."
  ),

  E(
    36,
    "The Letter From Future Eli",
    "Eli tells you what they were truly saving.",
    "You",
    "Future Letter",
    "normal",
    "blue",
    "letter",
    [
      "Behind the white door is a small room with no walls, only paper floating in the air like snow.",
      "Every page is a letter from Eli.",
      "Some are addressed to you.",
      "Some are addressed to versions of you who did not survive long enough to read them.",
      "One letter floats closer than the rest.",
      "\"If you are reading this, then I failed to leave cleanly.\"",
      "\"I know you think the story is about saving me.\"",
      "\"It was never that simple.\"",
      "\"I was saving the version of you who still knew how to love without turning love into a prison.\"",
      "\"Every loop made you braver.\"",
      "\"Every loop also made you smaller.\"",
      "\"You began remembering my death better than my life.\"",
      "\"So I built one final door.\"",
      "\"Not to bring myself back.\"",
      "\"To bring you back to yourself.\"",
      "\"Open Memory 000.\"",
    ],
    "Open Memory 000",
    "I was saving the version of you who still knew how to love.",
    "The back of the letter says: Open Memory 000."
  ),

  E(
    37,
    "The Memory You Must Not Open",
    "Truth requires your final safety.",
    "You",
    "Memory 000",
    "warning",
    "blue",
    "memory",
    [
      "Memory 000 waits inside the center of the room.",
      "It floats there, small and bright, like a thing that has been waiting for you to become tired enough to stop running.",
      "A warning appears above the memory:",
      "\"OPENING MEMORY 000 WILL REMOVE ONE FINAL RESET.\"",
      "\"AFTER THIS, THE NEXT CHOICE WILL BE REAL.\"",
      "You look at Eli.",
      "\"Why didn’t you tell me?\" you ask.",
      "Eli smiles like the question has killed them before.",
      "\"Because every time you knew the whole truth, you tried to die for me.\"",
      "The 11:11 PM clock begins counting backward from eleven seconds.",
      "Ten.",
      "Nine.",
      "Eight.",
      "Eli whispers your name.",
      "You press your hand into Memory 000.",
      "Everything becomes the first rain.",
    ],
    "Open Memory 000",
    "Some truths cost the last chance to avoid them.",
    "You return to the first 11:11 PM, before either of you understood the price."
  ),

  E(
    38,
    "The Day You Were Supposed to Die",
    "The original death was yours.",
    "You",
    "Original Street",
    "frozen",
    "red",
    "memory",
    [
      "Memory 000 begins before the loops.",
      "It is just an ordinary night.",
      "You are late.",
      "Eli is waiting across the street, pretending to be annoyed, smiling anyway.",
      "The message on your phone is from them:",
      "\"Don’t run. I’ll wait.\"",
      "You run.",
      "The car comes from nowhere.",
      "In every timeline after this, you believed it came for Eli.",
      "But the headlights are aimed at you.",
      "Eli sees the future one second before you do.",
      "They drop the coffee.",
      "They run into the road.",
      "Their hands hit your chest.",
      "You fall backward.",
      "The white light takes your place anyway.",
      "You see yourself on the pavement.",
      "Eli picks up the watch in your hand.",
      "The hands move backward.",
      "Eli pays the first price without knowing there will be another.",
    ],
    "Watch Eli Reset Time",
    "Before you tried to save Eli, Eli broke time to save you.",
    "Eli’s watch begins moving for the first time, and the first sacrifice chooses its owner."
  ),

  E(
    39,
    "The First Sacrifice",
    "You are Eli now.",
    "Eli",
    "Eli’s Watch",
    "frozen",
    "reversed",
    "watch",
    [
      "The screen reverses.",
      "The world turns warm orange, then white at the edges.",
      "The name in the corner changes.",
      "Traveler: Eli.",
      "For the first time, you are not chasing Eli through the timeline.",
      "You are inside the person who started running first.",
      "You feel their hands around the watch.",
      "You feel their panic when your body goes still in the original rain.",
      "Morning returns.",
      "You are Eli.",
      "You remember watching the person you love die.",
      "They do not.",
      "Then 11:11 PM comes again.",
      "This time death changes shape.",
      "A train platform.",
      "A stairwell.",
      "A fire alarm.",
      "A hospital corridor.",
      "A bridge in winter.",
      "You save them again.",
      "The watch cracks again.",
      "Another memory disappears.",
      "Again.",
      "Again.",
      "Timeline 106.",
      "You are Eli, standing beside another version of their body.",
      "The button does not say Restart.",
      "It says Save You.",
      "\"This is the 107th time I watch you die. I’m not letting go yet.\"",
    ],
    "Restart As Eli",
    "This is the 107th time I watch you die. I’m not letting go yet.",
    "Eli restarts the world and loses the memory of your first confession.",
    { specialMode: "eliPerspective" }
  ),

  E(
    40,
    "The Promise You Never Heard",
    "Eli made a vow at your grave.",
    "Eli",
    "Grave Memory",
    "warning",
    "orange",
    "memory",
    [
      "You remain Eli for one more memory.",
      "Only rain, a cemetery, and your own name carved into stone.",
      "Eli stands at your grave with the watch pressed against their chest.",
      "They speak to the grave like you can hear them.",
      "\"I tried once,\" Eli says.",
      "\"Then twice.\"",
      "\"Then I stopped counting because counting made it feel like I was choosing numbers instead of you.\"",
      "\"Every timeline asks me to give something up.\"",
      "\"My memories.\"",
      "\"My future.\"",
      "\"My name in your mouth.\"",
      "\"The way you looked at me the first time you knew you loved me.\"",
      "\"If time only understands debt, then let it take mine.\"",
      "\"I will break every timeline before I let this be the last one.\"",
      "The watch answers.",
      "\"Live long enough to forget this pain. I will remember it for both of us.\"",
    ],
    "Break The Timeline",
    "I will break every timeline before I let this be the last one.",
    "The system displays: Timeline 040 — Both Travelers Active."
  ),

  E(
    41,
    "Two Travelers, One Ending",
    "Both of you were trying. Both of you were losing.",
    "You",
    "Twin Watches",
    "warning",
    "blue",
    "watch",
    [
      "You return to your own body with Eli’s memories still burning inside you.",
      "For a moment, you cannot tell which heartbeat is yours.",
      "Yours is the one that kept chasing.",
      "Eli’s is the one that kept arriving first.",
      "The two broken watches lie between you on the floor, ticking in opposite directions.",
      "One tick for every time you tried to save Eli.",
      "One tick for every time Eli quietly saved you before you even knew you were in danger.",
      "You look at Eli, and the old lie finally breaks.",
      "They were never just the person waiting at the end of the loop.",
      "They were the other traveler.",
      "Every rescue from you triggered another sacrifice from Eli.",
      "Every sacrifice from Eli triggered another rescue from you.",
      "You were not fighting time.",
      "You were fighting each other’s grief.",
      "Eli touches the second watch and says:",
      "\"We loved each other so hard we turned love into a cage.\"",
      "The room shakes.",
      "Both watches stop at 11:11 PM.",
      "A white door appears where the wall used to be.",
      "Above it, a sentence forms in pale light:",
      "\"TWO TRAVELERS. ONE ENDING.\"",
    ],
    "Join The Memories",
    "Two people can love each other so much they become each other’s cage.",
    "Only one traveler may leave with memory intact."
  ),

  E(
    42,
    "The Room Between Seconds",
    "One second becomes a lifetime.",
    "You",
    "White Room",
    "frozen",
    "white",
    "door",
    [
      "At exactly 11:11 PM, the second freezes.",
      "You and Eli step through the white door into a room between moments.",
      "Outside, the world is paused.",
      "A raindrop hangs in the air.",
      "A car’s headlight waits without moving.",
      "A coffee cup spins above the pavement and never lands.",
      "Inside, one second stretches long enough to say everything you avoided.",
      "The room is empty except for two chairs and a small table.",
      "On the table: two cups of coffee.",
      "Eli sits across from you.",
      "They look less like someone about to die and more like someone finally allowed to be tired.",
      "\"I remember more than I told you,\" Eli says.",
      "You already know.",
      "But hearing it still hurts.",
      "\"I remembered the first time you died.\"",
      "\"I remembered the second.\"",
      "\"I remembered every version where you smiled at me and had no idea I had already buried you.\"",
      "Your throat closes.",
      "Eli reaches across the table.",
      "\"I didn’t hide it because I didn’t trust you.\"",
      "\"I hid it because every time you knew, you tried to take my place.\"",
    ],
    "Listen To Eli",
    "Some goodbyes need more than time can give.",
    "Eli admits they remembered every timeline."
  ),

  E(
    43,
    "All the Ways You Saved Me",
    "Eli sees the love hidden inside your failures.",
    "You",
    "Rescue Archive",
    "normal",
    "blue",
    "museum",
    [
      "The white room opens one wall like a screen.",
      "Every timeline where you tried to save Eli begins to play.",
      "You running through rain with your phone in your hand.",
      "You breaking a locked door with your shoulder.",
      "You lying to doctors to keep Eli inside a hospital.",
      "You buying train tickets with money you did not have.",
      "You mapping every street like grief could be solved with enough paper.",
      "You holding Eli’s hand so tightly that your own fingers shook.",
      "You choosing one more reset even after losing the sound of Eli’s laugh.",
      "You becoming smaller, colder, more desperate.",
      "Still trying.",
      "Still saying: one more time.",
      "Eli watches all of it.",
      "Not as the person being saved.",
      "As the person realizing what your love cost you.",
      "Their eyes fill with tears.",
      "\"You loved me so hard it almost destroyed you,\" Eli says.",
      "You try to apologize.",
      "Eli shakes their head.",
      "\"No.\"",
      "\"I needed to see it.\"",
      "\"Not because I wanted you to suffer.\"",
      "\"Because I needed to know the love was real before I asked you to release it.\"",
    ],
    "Let Eli Watch",
    "You loved me so hard it almost destroyed you.",
    "Eli reaches for your hand, but their fingers flicker."
  ),

  E(
    44,
    "All the Ways I Saved You",
    "Eli’s sacrifices outnumber your memories.",
    "You",
    "Eli Archive",
    "warning",
    "orange",
    "museum",
    [
      "Now the room changes color.",
      "Cold blue becomes warm orange.",
      "Eli’s archive opens.",
      "There are more timelines than yours.",
      "Dozens.",
      "Hundreds.",
      "Eli pulling you from fires you never remembered.",
      "Eli missing trains so you would not board the one that crashed.",
      "Eli deleting messages so you would take a different street.",
      "Eli staying behind in collapsing rooms while you woke safely in another morning.",
      "Eli lying to you because the truth made you reckless.",
      "Eli smiling over coffee while remembering your funeral.",
      "Eli standing at your grave, promising to break time again.",
      "The archive counter climbs.",
      "047.",
      "086.",
      "107.",
      "144.",
      "231.",
      "300.",
      "Then the counter breaks.",
      "The room cannot count Eli’s sacrifices anymore.",
      "You look at Eli.",
      "They look embarrassed, as if being loved this much was less frightening than being seen.",
      "\"I didn’t want you to owe me,\" Eli says.",
      "\"I wanted you to live without knowing there was a debt.\"",
      "You whisper:",
      "\"Why?\"",
      "Eli answers like the truth is simple.",
      "\"Because your life was not a debt to me.\"",
      "\"It was the future I kept choosing.\"",
    ],
    "Watch Eli’s Archive",
    "You thought Eli was waiting to be saved. Eli was the first rescuer.",
    "The museum cannot count Eli’s remaining sacrifices."
  ),

  E(
    45,
    "The Timeline That Wants One of You",
    "The enemy is not evil. It is balance.",
    "You",
    "Timeline Core",
    "collapse",
    "red",
    "door",
    [
      "The white room falls away.",
      "You stand before the timeline core.",
      "It does not look like a monster.",
      "It looks like a rule made visible.",
      "A circle of light, split down the center.",
      "One side red.",
      "One side white.",
      "The core does not hate you.",
      "That makes it worse.",
      "Hatred can be argued with.",
      "A rule can only be paid.",
      "Words appear in the air:",
      "\"TWO TRAVELERS CANNOT KEEP THE SAME ENDING.\"",
      "\"ONE MAY LIVE WITH MEMORY.\"",
      "\"ONE MUST BECOME THE GOODBYE.\"",
      "You step forward immediately.",
      "You say you will be the goodbye.",
      "You say it before fear can stop you.",
      "Eli grabs your arm.",
      "\"No.\"",
      "You turn.",
      "Their face is calm in the most terrifying way.",
      "Not calm because they are not afraid.",
      "Calm because they have already made this choice too many times.",
      "\"You don’t get to save me by throwing away the life I spent everything to protect.\"",
      "The core asks:",
      "\"Save the one you love, or become the one they lose.\"",
    ],
    "Face The Core",
    "A rule does not need cruelty to break your heart.",
    "The core asks: Save the one you love, or become the one they lose."
  ),

  E(
    46,
    "The Choice That Isn’t a Choice",
    "You try to sacrifice yourself, but Eli already did.",
    "You",
    "Final Command",
    "warning",
    "red",
    "message",
    [
      "You choose to die so Eli can live.",
      "For one second, the timeline accepts.",
      "The white half of the core turns toward you.",
      "The broken watch heats in your hand.",
      "You feel the old road beneath your feet.",
      "You feel the first car coming again.",
      "You almost feel relief.",
      "Then the command is rejected.",
      "A message from Eli appears before your choice can complete.",
      "\"Do not let them die for me again.\"",
      "You stare at the words.",
      "Again.",
      "Eli steps beside you.",
      "\"I locked your death out of the final timeline,\" they say.",
      "\"When?\"",
      "Eli smiles sadly.",
      "\"Before you even knew there was a final timeline.\"",
      "The core flashes.",
      "\"SELF-SACRIFICE OVERRIDE DENIED.\"",
      "\"PRIMARY DEBT ALREADY PAID.\"",
      "You turn to Eli, furious and heartbroken.",
      "\"You had no right.\"",
      "Eli’s voice breaks.",
      "\"I know.\"",
      "\"But I loved you before I learned how to ask permission from time.\"",
    ],
    "Override The Command",
    "You cannot sacrifice yourself for someone who already sacrificed first.",
    "Eli locked your death out of the final timeline."
  ),

  E(
    47,
    "Eli Remembers Everything",
    "Eli was never forgetting. Eli was protecting you.",
    "You",
    "Full Memory",
    "frozen",
    "orange",
    "memory",
    [
      "The final wall of the archive opens.",
      "And now you understand the cruelest truth.",
      "Eli did not slowly remember the loops.",
      "Eli remembered all of them from the beginning.",
      "Every reset.",
      "Every hospital.",
      "Every red station.",
      "Every version of you dying before breakfast, after midnight, under winter rain, beside a train track, inside a burning room, in a world where you never met.",
      "Every time you looked at Eli like it was the first time, Eli had already lost you hundreds of times.",
      "They still smiled.",
      "They still made coffee.",
      "They still asked if you slept well.",
      "They still let you believe the morning was new.",
      "Not because they were cruel.",
      "Because they thought the truth would destroy you.",
      "Eli wipes their face with the back of their hand.",
      "\"I wanted you to have at least a few hours where you were not grieving.\"",
      "\"Even if I had to grieve for both of us.\"",
      "You reach for them.",
      "This time, they do not pull away.",
      "Their body begins to fade from the edges inward.",
      "Warm light shines through their hands.",
      "\"I am so tired,\" Eli whispers.",
      "\"But I would still choose it again, if the only other ending was you gone.\"",
    ],
    "Hold Eli",
    "Every time you looked at me like it was the first time, I had already lost you hundreds of times.",
    "Eli’s body begins to fade from the white room."
  ),

  E(
    48,
    "The Final Rescue",
    "Eli moves first one last time.",
    "You",
    "Final Watch",
    "collapse",
    "red",
    "watch",
    [
      "You prepare one final rescue.",
      "A loophole.",
      "A reversal.",
      "A way to force the timeline to take you instead.",
      "You have learned enough now to be dangerous.",
      "You know where the core splits.",
      "You know when the command accepts sacrifice.",
      "You know which second still trembles around the first accident.",
      "But Eli smiles through tears.",
      "They were earlier again.",
      "They always were.",
      "Eli places their watch against yours.",
      "The two broken faces align.",
      "Every remaining timeline permission transfers into your watch.",
      "Every possible death meant for you locks behind a door with Eli’s name on it.",
      "You grab Eli’s wrist.",
      "\"Stop.\"",
      "Eli shakes their head.",
      "\"This is the only rescue I have left.\"",
      "Their body becomes almost transparent.",
      "Behind them, thousands of failed timelines begin closing like tired eyes.",
      "\"I am not saving you from death this time,\" Eli says.",
      "\"I am saving you from becoming someone who only knows how to chase it.\"",
      "The final watch clicks.",
      "The red station disappears.",
      "The museum begins to collapse.",
      "Eli begins disappearing from every timeline at once.",
    ],
    "Stop Eli",
    "The final rescue was never yours to perform.",
    "Eli begins disappearing from every timeline at once."
  ),

  E(
    49,
    "You Were Never the Only One Trying",
    "The last door was Eli’s gift.",
    "You",
    "The Last Door",
    "frozen",
    "white",
    "door",
    [
      "The last door appears after the museum falls silent.",
      "It is not red.",
      "It is not blue.",
      "It is warm white, like morning after a night that took too much.",
      "Eli stands beside it, almost made of light now.",
      "You understand before they speak.",
      "Timeline 050 was not created by you.",
      "It was created by Eli using every memory they had left.",
      "Not as a world where Eli survives.",
      "As a world where you finally can.",
      "You shake your head.",
      "\"I don’t want a timeline without you.\"",
      "Eli smiles, and it hurts because it is the same smile they gave you over coffee before all of this began.",
      "\"I know.\"",
      "\"That is why I built one where you can miss me and still live.\"",
      "The sentence breaks something open inside you.",
      "Eli places their watch in your hand.",
      "It is no longer ticking.",
      "\"You were never the only one trying,\" they say.",
      "\"But now you have to be the one who lives.\"",
      "The Last Door opens into morning light.",
      "No siren.",
      "No countdown.",
      "No 11:11 PM.",
      "Only two cups of coffee waiting on a table.",
    ],
    "Enter The Last Timeline",
    "You were never the only one trying.",
    "The Last Door opens into morning light."
  ),

  E(
    50,
    "The Last Timeline",
    "There is no rescue left. Only goodbye.",
    "You",
    "Two Coffees",
    "frozen",
    "white",
    "final",
    [
      "You enter the last timeline.",
      "There is no accident.",
      "No countdown.",
      "No siren.",
      "No red station waiting under the city.",
      "No museum of failed worlds.",
      "No watch screaming against your wrist.",
      "Only a quiet room, morning light, and two cups of coffee on the table.",
      "Eli is sitting across from you.",
      "Alive enough to break your heart.",
      "They smile like nothing ever broke, but their eyes already know this is borrowed time.",
      "For one impossible moment, you let yourself believe you saved them.",
      "You let yourself believe every loop, every loss, every shattered memory finally bought this small room.",
      "Then Eli reaches across the table and turns your palm upward.",
      "In your hand is the final watch.",
      "Both sets of hands are gone.",
      "No 11:11 PM.",
      "No reset.",
      "No way back.",
      "Eli says your name the way they did before time learned how to take it from you.",
      "\"This is not the world where I survive.\"",
      "You cannot move.",
      "\"This is the world where you finally do.\"",
      "The room fills slowly with warm white light.",
      "Not harsh like the first accident.",
      "Gentle.",
      "Like dawn deciding not to ask permission.",
      "You tell Eli you are sorry.",
      "For every failed rescue.",
      "For every timeline where love became panic.",
      "For every moment you tried to keep them without asking what they had already given.",
      "Eli shakes their head.",
      "\"I didn’t leave because you failed to save me.\"",
      "Their fingers tighten around yours.",
      "\"I left because I finally saved you.\"",
      "You break.",
      "Not loudly.",
      "Not dramatically.",
      "Just enough that every version of you who kept running finally stops.",
      "Eli smiles through tears.",
      "\"In every timeline, I chose the one where you lived.\"",
      "\"Not because I wanted to leave.\"",
      "\"Because loving you meant giving you a future I could not stay in.\"",
      "The coffee between you is still warm.",
      "The window is open.",
      "Somewhere outside, the world continues without knowing what it cost to reach morning.",
      "Eli looks toward the door.",
      "Then back at you.",
      "\"Don’t make my goodbye smaller by turning it into your prison.\"",
      "\"Live the life I kept giving back to you.\"",
      "The final choice appears.",
    ],
    "Choose",
    "In every timeline, I chose the one where you lived. Not because I wanted to leave. Because loving you meant giving you a future I could not stay in.",
    "Hold On, or Let Go.",
    {
      specialMode: "finalChoice",
      finalChoices: {
        holdOn: {
          maxBeforeCollapse: 3,
          buttonText: "Hold On",
          lines: [
            "You hold on.",
            "The room shudders, not with anger, but with exhaustion.",
            "Eli closes their eyes as if they expected this and feared it anyway.",
            "The coffee goes cold.",
            "The window darkens.",
            "The watch tries to grow hands again, but they twist into broken lines.",
            "You hold on harder.",
            "Eli’s face blurs at the edges.",
            "Their voice becomes distant, like a recording played too many times.",
            "\"Please,\" Eli whispers. \"Do not make me watch you lose yourself again.\"",
            "You refuse.",
            "The room cracks.",
            "The word Eli becomes harder to read.",
            "The letters scatter across the table like ash.",
            "Your obsession is tearing the world apart. Is this what love looks like to you?",
            "11:11 PM returns, violent and red, forcing itself onto every wall.",
            "Eli reaches for your face, but their hand passes through you.",
            "\"If you hold on to my ending, you will lose the life I saved.\"",
            "The choice returns.",
          ],
        },
        letGo: {
          buttonText: "Let Go",
          successTitle: "Final Goodbye",
          quote:
            "In every timeline, I chose the one where you lived. Not because I wanted to leave. Because loving you meant giving you a future I could not stay in.",
          lines: [
            "You let go.",
            "Not because you stop loving Eli.",
            "Because you finally understand that love was never supposed to be a hand around someone’s leaving.",
            "The broken watch stops screaming.",
            "The red station closes its doors.",
            "The museum lights turn off one by one, not erased, only at rest.",
            "Every failed timeline folds itself into a single warm breath.",
            "Eli exhales like they have been holding the universe together with their ribs.",
            "They smile.",
            "Not because leaving is easy.",
            "Because you finally understood the gift.",
            "\"I didn’t leave because you failed to save me.\"",
            "\"I left because I finally saved you.\"",
            "You nod, even though nodding feels like breaking.",
            "Eli stands.",
            "The morning light passes through them gently.",
            "Before they disappear, they touch the final watch in your hand.",
            "The glass clears.",
            "Inside, where the hands used to be, there is one last message:",
            "\"Live.\"",
            "Eli’s final words arrive like sunrise:",
            "\"Now live the life I kept giving back to you.\"",
            "When the light fades, you are alone at the table.",
            "Two cups of coffee.",
            "One empty chair.",
            "One life returned.",
            "And for the first time, the clock moves past 11:11 PM.",
          ],
          finalLine: "Now live the life I kept giving back to you.",
        },
      },
    }
  ),
];

const timelineClockModes = {
  normal: {
    label: "Normal",
    description: "The 11:11 PM clock flickers faintly.",
  },
  warning: {
    label: "Warning",
    description: "The 11:11 PM clock shakes, brightens, or begins counting down.",
  },
  frozen: {
    label: "Frozen",
    description: "The clock freezes at 11:11 PM. Time refuses to move.",
  },
  collapse: {
    label: "Collapse",
    description: "The clock glitches, tears, and corrupts the screen.",
  },
};

const timelineVisualModes = {
  blue: {
    label: "Cold Blue",
    description: "Main player perspective. Grief, mystery, time pressure.",
  },
  red: {
    label: "Red Station",
    description: "Timeline danger, rule exposure, universe-level mystery.",
  },
  orange: {
    label: "Warm Orange",
    description: "Eli perspective, sacrifice, memory warmth.",
  },
  white: {
    label: "Warm White",
    description: "Final timeline, acceptance, letting go.",
  },
  reversed: {
    label: "Reversed Eli Mode",
    description: "EP.39 perspective flip. Player becomes Eli.",
  },
};

const timelineArchiveFragments = timelineEpisodes.map((episode) => ({
  id: episode.id,
  title: episode.title,
  fragmentType: episode.fragmentType,
  prop: episode.prop,
  traveler: episode.traveler,
  quote: episode.quote,
}));

const timelineFinalLogic = {
  finalEpisodeId: 50,
  holdOnStorageKey: "timeline_hold_on_count",
  archiveStorageKey: "timeline_archive_fragments",
  completedStorageKey: "timeline_completed",
  letGoUnlocksFinalMemory: true,
  finalMemoryCard: {
    title: "Save This Timeline",
    quote:
      "In every timeline, I chose the one where you lived. Not because I wanted to leave. Because loving you meant giving you a future I could not stay in.",
    subtitle: "The Last Timeline · Final Memory",
    shareText:
      "I didn’t leave because you failed to save me. I left because I finally saved you.",
  },
};

function getTimelineEpisode(id) {
  return timelineEpisodes.find((episode) => episode.id === Number(id)) || null;
}

function getNextTimelineEpisode(id) {
  const nextId = Number(id) + 1;
  return getTimelineEpisode(nextId);
}

function getTimelineProgress(id) {
  const current = Math.min(Math.max(Number(id) || 1, 1), timelineEpisodes.length);
  return {
    current,
    total: timelineEpisodes.length,
    percent: Math.round((current / timelineEpisodes.length) * 100),
  };
}

function isEliPerspectiveEpisode(id) {
  const episode = getTimelineEpisode(id);
  return episode
    ? episode.traveler === "Eli" || episode.specialMode === "eliPerspective"
    : false;
}

function isFinalTimelineEpisode(id) {
  const episode = getTimelineEpisode(id);
  return episode ? episode.specialMode === "finalChoice" : false;
}

window.timelineMeta = timelineMeta;
window.timelineEpisodes = timelineEpisodes;
window.timelineClockModes = timelineClockModes;
window.timelineVisualModes = timelineVisualModes;
window.timelineArchiveFragments = timelineArchiveFragments;
window.timelineFinalLogic = timelineFinalLogic;

window.getTimelineEpisode = getTimelineEpisode;
window.getNextTimelineEpisode = getNextTimelineEpisode;
window.getTimelineProgress = getTimelineProgress;
window.isEliPerspectiveEpisode = isEliPerspectiveEpisode;
window.isFinalTimelineEpisode = isFinalTimelineEpisode;

window.TIMELINE_META = timelineMeta;
window.TIMELINE_EPISODES = timelineEpisodes;
window.TIMELINE_CLOCK_MODES = timelineClockModes;
window.TIMELINE_VISUAL_MODES = timelineVisualModes;
window.TIMELINE_ARCHIVE_FRAGMENTS = timelineArchiveFragments;
window.TIMELINE_FINAL_LOGIC = timelineFinalLogic;
